#!/usr/bin/env python3
"""
TeaVault — Embed Images as CSS Data URIs
Run once from your Terminal:
  python3 /Users/amn/Documents/GitHub/Claude/TeaVault/embed-images.py

This reads all generated PNGs from the Antigravity brain directory,
base64-encodes them, and writes them directly into images.css as
data: URIs — so the site works instantly with no file copying needed.
"""
import os, base64

B = "/Users/amn/.gemini/antigravity/brain/1b11ecb9-0200-4698-b03a-9342c5a91438"
CSS_OUT = "/Users/amn/Documents/GitHub/Claude/TeaVault/images.css"

# Map: (source filename in brain) -> (css_name used in rules)
IMAGES = [
    ("hero_tea_garden_1775633055581.png",            "hero"),
    ("tea_gyokuro_1775633069580.png",                "tea-gyokuro"),
    ("tea_dancong_1775633083422.png",                "tea-dancong"),
    ("tea_darjeeling_1775633193493.png",             "tea-darjeeling"),
    ("gallery_uji_garden_1775633208050.png",         "gallery-uji"),
    ("gallery_gongfu_ceremony_1775633225716.png",    "gallery-gongfu"),
    ("gallery_darjeeling_harvest_1775633253513.png", "gallery-darjeeling"),
    ("gallery_yixing_clay_1775633270209.png",        "gallery-yixing"),
    ("gallery_moroccan_atay_1775633285534.png",      "gallery-morocco"),
    ("gallery_japanese_ceremony_1775633312266.png",  "gallery-japan-ceremony"),
    ("gallery_taiwan_garden_1775633327947.png",      "gallery-taiwan"),
    ("gallery_turkish_cay_1775633343061.png",        "gallery-turkey"),
    ("gallery_kenya_estate_1775633371878.png",       "gallery-kenya"),
    ("gallery_teapot_market_1775633388418.png",      "gallery-teapot-market"),
    ("culture_chado_1775633403446.png",              "culture-japan"),
    ("culture_gongfu_1775633435039.png",             "culture-china"),
    ("culture_indian_chai_1775633449945.png",        "culture-india"),
]

print("📷 Reading and encoding images...")
uris = {}
for fname, key in IMAGES:
    path = os.path.join(B, fname)
    try:
        with open(path, "rb") as f:
            data = f.read()
        b64 = base64.b64encode(data).decode("ascii")
        uris[key] = f"data:image/png;base64,{b64}"
        print(f"  ✅ {key}  ({len(data)//1024}KB → {len(b64)//1024}KB b64)")
    except Exception as e:
        print(f"  ❌ {key}: {e}")
        uris[key] = None

def u(key):
    """Return CSS url() value for a key, falling back to a solid colour."""
    if uris.get(key):
        return f"url('{uris[key]}')"
    return "none"

print("\n✍️  Writing images.css ...")

css = f"""/* ============================================================
   TEAVAULT — Embedded Image Data URIs
   Auto-generated by embed-images.py — do not edit manually.
   Regenerate by running:  python3 embed-images.py
   ============================================================ */

/* ── Hero Background ── */
.hero-layer-1 {{
  background-image: {u('hero')} !important;
  background-size: cover;
  background-position: center 30%;
}}
.hero-layer-2 {{
  background-image: {u('hero')} !important;
  background-size: cover;
  background-position: center 60%;
  opacity: 0.3;
  mix-blend-mode: luminosity;
}}

/* ── Featured Tea Cards ── */
.featured-card:nth-child(1) .featured-card-img,
.featured-card-img-placeholder.featured-img-1 {{
  background-image: {u('tea-gyokuro')} !important;
  background-size: cover; background-position: center;
}}
.featured-card:nth-child(2) .featured-card-img,
.featured-card-img-placeholder.featured-img-2 {{
  background-image: {u('tea-dancong')} !important;
  background-size: cover; background-position: center;
}}
.featured-card:nth-child(3) .featured-card-img,
.featured-card-img-placeholder.featured-img-3 {{
  background-image: {u('tea-darjeeling')} !important;
  background-size: cover; background-position: center;
}}

/* ── Homepage Gallery Preview ── */
.gal-img-1 {{ background-image: {u('gallery-uji')} !important; background-size: cover; background-position: center; }}
.gal-img-2 {{ background-image: {u('gallery-gongfu')} !important; background-size: cover; background-position: center; }}
.gal-img-3 {{ background-image: {u('gallery-darjeeling')} !important; background-size: cover; background-position: center; }}
.gal-img-4 {{ background-image: {u('gallery-morocco')} !important; background-size: cover; background-position: center; }}
.gal-img-5 {{ background-image: {u('gallery-yixing')} !important; background-size: cover; background-position: center; }}

/* ── Education Hub Articles ── */
.edu-art-img-1 {{ background-image: {u('gallery-gongfu')} !important; background-size: cover; background-position: center; }}
.edu-art-img-2 {{ background-image: {u('gallery-darjeeling')} !important; background-size: cover; background-position: center; }}
.edu-art-img-3 {{ background-image: {u('culture-china')} !important; background-size: cover; background-position: center; }}

/* ── B2B Teaser Images ── */
.b2b-img-main  {{ background-image: {u('gallery-teapot-market')} !important; background-size: cover; background-position: center; }}
.b2b-img-accent {{ background-image: {u('gallery-kenya')} !important; background-size: cover; background-position: center; }}

/* ── Gallery Page Items ── */
.gallery-item:nth-child(1)  {{ background-image: {u('gallery-uji')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(2)  {{ background-image: {u('gallery-gongfu')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(3)  {{ background-image: {u('gallery-darjeeling')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(4)  {{ background-image: {u('gallery-yixing')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(5)  {{ background-image: {u('gallery-morocco')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(6)  {{ background-image: {u('gallery-japan-ceremony')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(7)  {{ background-image: {u('gallery-taiwan')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(8)  {{ background-image: {u('gallery-teapot-market')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(9)  {{ background-image: {u('gallery-turkey')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(10) {{ background-image: {u('gallery-darjeeling')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(11) {{ background-image: {u('gallery-turkey')} !important; background-size: cover; background-position: center; }}
.gallery-item:nth-child(12) {{ background-image: {u('gallery-kenya')} !important; background-size: cover; background-position: center; }}

/* ── Education — World Cultures Cards ── */
.culture-card:nth-child(1) .culture-card-img {{ background-image: {u('culture-japan')} !important; background-size: cover; background-position: center; }}
.culture-card:nth-child(2) .culture-card-img {{ background-image: {u('culture-china')} !important; background-size: cover; background-position: center; }}
.culture-card:nth-child(3) .culture-card-img {{ background-image: {u('gallery-morocco')} !important; background-size: cover; background-position: center; }}
.culture-card:nth-child(4) .culture-card-img {{ background-image: {u('culture-india')} !important; background-size: cover; background-position: center; }}
.culture-card:nth-child(5) .culture-card-img {{ background-image: {u('gallery-japan-ceremony')} !important; background-size: cover; background-position: top; }}
.culture-card:nth-child(6) .culture-card-img {{ background-image: {u('gallery-turkey')} !important; background-size: cover; background-position: center; }}
.culture-card:nth-child(7) .culture-card-img {{ background-image: {u('gallery-taiwan')} !important; background-size: cover; background-position: center; }}
.culture-card:nth-child(8) .culture-card-img {{ background-image: {u('gallery-kenya')} !important; background-size: cover; background-position: center; }}

/* ── Tea type cards in catalog ── */
.tcard-green  .tea-card-img-inner {{ background-image: {u('tea-gyokuro')} !important; background-size: cover; background-position: center; }}
.tcard-oolong .tea-card-img-inner {{ background-image: {u('tea-dancong')} !important; background-size: cover; background-position: center; }}
.tcard-black  .tea-card-img-inner {{ background-image: {u('tea-darjeeling')} !important; background-size: cover; background-position: center; }}

/* ── Page hero override ── */
.page-hero {{
  background-image: {u('hero')} !important;
  background-size: cover;
  background-position: center 40%;
}}
"""

with open(CSS_OUT, "w") as f:
    f.write(css)

size_kb = os.path.getsize(CSS_OUT) // 1024
print(f"  ✅ images.css written ({size_kb}KB)")
print(f"\n🎉 Done! Refresh http://localhost:8765 to see all photos live.")
