#!/usr/bin/env node
/**
 * RebelThreads — Printify Setup & Sync Script
 * 
 * Run from the backend directory:
 *   node scripts/setup.js
 * 
 * No npm install needed — uses Node 18+ built-in fetch.
 * Reads credentials directly from backend/.env
 * 
 * What it does:
 *   1. Verifies your Printify API key & confirms your Shop ID
 *   2. Lists all products with their variant IDs
 *   3. Auto-matches your Printify products to the RebelThreads catalog
 *   4. Writes the updated catalog.js file automatically
 *   5. Registers Printify webhooks (if PUBLIC_URL is set)
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

// ─── Load .env manually (no dotenv needed) ──────────────────────────────────
function loadEnv() {
  const envPath = join(ROOT, '.env');
  try {
    const raw = readFileSync(envPath, 'utf8');
    raw.split('\n').forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const [key, ...rest] = trimmed.split('=');
      if (key && rest.length) process.env[key.trim()] = rest.join('=').trim();
    });
  } catch {
    console.error('❌  Could not read backend/.env — make sure it exists!');
    process.exit(1);
  }
}

// ─── Printify API helper ─────────────────────────────────────────────────────
async function printify(path) {
  const apiKey = process.env.PRINTIFY_API_KEY;
  if (!apiKey) throw new Error('PRINTIFY_API_KEY not set in .env');
  const res = await fetch(`https://api.printify.com/v1${path}`, {
    headers: { Authorization: `Bearer ${apiKey}` }
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.message || JSON.stringify(data));
  return data;
}

// ─── The slogan names in our catalog, by ID ──────────────────────────────────
const CATALOG_NAMES = {
  1: 'QUESTION EVERYTHING',
  2: 'NO FUTURE',
  3: 'BORN TO RAISE HELL',
  4: 'ANARCHY IN THE USA',
  5: 'DISCO SUCKS',
  6: 'FIGHT THE POWER',
  7: 'TUNE IN DROP OUT',
  8: 'I AM NOT YOUR TARGET MARKET',
  9: 'STAY WILD',
  10: 'DISRUPT NICELY',
  11: 'UNFOLLOW THE HERD',
  12: 'THINK FOR YOURSELF',
  13: 'MAKE NOISE QUIETLY',
  14: 'NOT AVAILABLE',
  15: 'QUIET RIOT',
  16: 'NO PERMISSION NEEDED',
  17: 'KINDLY DISAGREE',
  18: 'SELECTIVE SILENCE',
};

// ─── Try to match a Printify product title to a catalog entry ────────────────
function matchCatalogId(printifyTitle) {
  const titleUpper = printifyTitle.toUpperCase();
  for (const [id, slogan] of Object.entries(CATALOG_NAMES)) {
    if (titleUpper.includes(slogan) || slogan.includes(titleUpper)) {
      return parseInt(id);
    }
  }
  return null;
}

// ─── Parse variants to extract size-to-ID mapping ───────────────────────────
function extractSizeVariants(variants) {
  const sizes = ['S', 'M', 'L', 'XL', '2XL', 'XXL'];
  const result = {};
  for (const v of variants) {
    const titleUpper = (v.title || '').toUpperCase();
    for (const size of sizes) {
      const key = size === 'XXL' ? '2XL' : size;
      if (titleUpper.includes(`/ ${size}`) || titleUpper.startsWith(size) || titleUpper.includes(` ${size}`) || titleUpper === size) {
        if (!result[key]) result[key] = v.id;
      }
    }
  }
  return result;
}

// ─── Generate catalog.js content ─────────────────────────────────────────────
function generateCatalogJs(mapping) {
  const entries = Object.entries(CATALOG_NAMES).map(([id, slogan]) => {
    const match = mapping[parseInt(id)];
    const printifyProductId = match ? `'${match.printifyProductId}'` : `'FILL_ME'`;
    const variants = match ? match.variants : {};
    const variantsStr = ['S', 'M', 'L', 'XL', '2XL'].map(s => {
      const variantId = variants[s] ?? null;
      return `    ${s}: ${variantId}`;
    }).join(',\n');

    return `  ${id}: {
    slogan: '${slogan}',
    printifyProductId: ${printifyProductId},
    variants: {
${variantsStr},
    },
  }`;
  });

  return `/**
 * lib/catalog.js — AUTO-GENERATED by scripts/setup.js on ${new Date().toISOString()}
 * Maps RebelThreads shirt IDs → Printify product + variant lookup.
 * Re-run "node scripts/setup.js" to refresh.
 */

export const CATALOG = {
${entries.join(',\n')},
};

export function resolveVariant(shirtId, size) {
  const product = CATALOG[shirtId];
  if (!product) throw new Error(\`Unknown shirt ID: \${shirtId}\`);
  const variantId = product.variants[size];
  if (!variantId) throw new Error(\`Variant not configured for shirt \${shirtId} / size \${size}.\`);
  return { printifyProductId: product.printifyProductId, variantId };
}
`;
}

// ─── Register webhooks ───────────────────────────────────────────────────────
async function registerWebhooks(shopId) {
  const publicUrl = process.env.PUBLIC_URL;
  if (!publicUrl || publicUrl.includes('localhost')) {
    console.log('⚠️   Skipping webhooks — PUBLIC_URL not set to a live domain.');
    console.log('    Set PUBLIC_URL=https://your-api-domain.com in .env to enable.\n');
    return;
  }

  const events = ['order:created', 'order:sent-to-production', 'shipment:created', 'shipment:delivered'];
  const endpointBase = `${publicUrl}/webhooks/printify`;

  for (const topic of events) {
    try {
      // Check if already registered
      const existing = await printify(`/shops/${shopId}/webhooks.json`);
      const alreadySet = (existing.data || existing).some(w => w.topic === topic);
      if (alreadySet) {
        console.log(`  ✓  Webhook already registered: ${topic}`);
        continue;
      }
      await fetch(`https://api.printify.com/v1/shops/${shopId}/webhooks.json`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.PRINTIFY_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ topic, url: endpointBase }),
      });
      console.log(`  ✅  Registered webhook: ${topic}`);
    } catch (e) {
      console.log(`  ❌  Failed to register ${topic}: ${e.message}`);
    }
  }
}

// ─── MAIN ────────────────────────────────────────────────────────────────────
async function main() {
  console.log('\n\x1b[31m  ██████╗ ███████╗██████╗ ███████╗██╗  \x1b[0m');
  console.log('\x1b[31m  ██╔══██╗██╔════╝██╔══██╗██╔════╝██║  \x1b[0m');
  console.log('\x1b[31m  ██████╔╝█████╗  ██████╔╝█████╗  ██║  \x1b[0m');
  console.log('\x1b[31m  ██╔══██╗██╔══╝  ██╔══██╗██╔══╝  ██║  \x1b[0m');
  console.log('\x1b[31m  ██║  ██║███████╗██████╔╝███████╗███████╗\x1b[0m');
  console.log('\x1b[31m  ╚═╝  ╚═╝╚══════╝╚═════╝ ╚══════╝╚══════╝\x1b[0m');
  console.log('\x1b[2m  REBELTHREADS — Printify Setup & Sync\x1b[0m\n');

  loadEnv();

  // 1. Verify credentials & get Shop ID
  console.log('🔍  Step 1: Verifying Printify credentials...');
  let shopId = process.env.PRINTIFY_SHOP_ID;
  try {
    const shops = await printify('/shops.json');
    console.log(`  ✅  API key valid! Found ${shops.length} shop(s):\n`);
    shops.forEach(s => {
      const match = s.id.toString() === shopId ? ' ← CURRENT' : '';
      console.log(`      ID: ${s.id}  |  Title: "${s.title}"  |  Channel: ${s.sales_channel}${match}`);
    });

    if (shops.length === 1) {
      shopId = shops[0].id.toString();
      if (shopId !== process.env.PRINTIFY_SHOP_ID) {
        console.log(`\n  ⚠️   Correcting Shop ID from ${process.env.PRINTIFY_SHOP_ID} → ${shopId}`);
        const envPath = join(ROOT, '.env');
        let envContent = readFileSync(envPath, 'utf8');
        envContent = envContent.replace(
          /PRINTIFY_SHOP_ID=.*/,
          `PRINTIFY_SHOP_ID=${shopId}`
        );
        writeFileSync(envPath, envContent);
        console.log(`  ✅  Updated .env with correct Shop ID: ${shopId}`);
      } else {
        console.log(`\n  ✅  Shop ID in .env is correct: ${shopId}`);
      }
    } else if (shops.length > 1) {
      console.log(`\n  ℹ️   Multiple shops found. Using ID: ${shopId} (from .env)`);
    }
  } catch (e) {
    console.error(`\n  ❌  Printify API error: ${e.message}\n`);
    process.exit(1);
  }

  // 2. Fetch products
  console.log('\n🛍️   Step 2: Fetching your Printify products...');
  let allProducts = [];
  try {
    let page = 1;
    while (true) {
      const data = await printify(`/shops/${shopId}/products.json?limit=20&page=${page}`);
      const products = data.data || data;
      if (!products.length) break;
      allProducts = allProducts.concat(products);
      if (products.length < 20) break;
      page++;
    }
    console.log(`  ✅  Found ${allProducts.length} product(s) in your Printify shop.\n`);
  } catch (e) {
    console.error(`  ❌  Could not fetch products: ${e.message}`);
    process.exit(1);
  }

  if (allProducts.length === 0) {
    console.log('  ⚠️   No products found in your Printify shop.');
    console.log('  Create your products in Printify first, then re-run this script.\n');
    process.exit(0);
  }

  // 3. Match products to catalog
  console.log('🗺️   Step 3: Matching Printify products to RebelThreads catalog...\n');
  const catalogMapping = {};
  const unmatchedPrintify = [];
  const unmatchedCatalog = new Set(Object.keys(CATALOG_NAMES).map(Number));

  for (const product of allProducts) {
    const catalogId = matchCatalogId(product.title);
    const variants = extractSizeVariants(product.variants || []);
    const variantCount = Object.keys(variants).length;

    if (catalogId) {
      catalogMapping[catalogId] = {
        printifyProductId: product.id,
        variants,
      };
      unmatchedCatalog.delete(catalogId);
      console.log(`  ✅  Matched: "${product.title}" → Catalog #${catalogId} (${variantCount} size(s))`);
    } else {
      unmatchedPrintify.push(product.title);
      console.log(`  ❓  No match:  "${product.title}" (${variantCount} size(s)) — not in catalog`);
    }
  }

  if (unmatchedCatalog.size > 0) {
    console.log(`\n  ⚠️   ${unmatchedCatalog.size} catalog entries have no Printify product yet:`);
    unmatchedCatalog.forEach(id => console.log(`      • #${id}: ${CATALOG_NAMES[id]}`));
  }

  // 4. Write catalog.js
  console.log('\n✍️   Step 4: Writing catalog.js...');
  const catalogContent = generateCatalogJs(catalogMapping);
  const catalogPath = join(ROOT, 'lib', 'catalog.js');
  writeFileSync(catalogPath, catalogContent);
  console.log(`  ✅  catalog.js updated at: ${catalogPath}`);
  console.log(`  ✅  ${Object.keys(catalogMapping).length} of ${Object.keys(CATALOG_NAMES).length} products mapped.\n`);

  // 5. Register webhooks
  console.log('🔔  Step 5: Registering Printify webhooks...');
  await registerWebhooks(shopId);

  // 6. Summary
  const matched = Object.keys(catalogMapping).length;
  const total = Object.keys(CATALOG_NAMES).length;
  const ready = matched === total;

  console.log('\n' + '─'.repeat(55));
  console.log(`\n  REBELTHREADS SETUP ${ready ? '✅ COMPLETE' : '⚠️  PARTIAL'}\n`);
  console.log(`  Products mapped: ${matched}/${total}`);
  if (!ready) {
    console.log(`\n  To complete setup:`);
    console.log(`  1. Create the missing products in Printify`);
    console.log(`  2. Re-run: node scripts/setup.js`);
  } else {
    console.log(`\n  You're ready to take orders! 🚀`);
    console.log(`  Start the server: npm run dev`);
  }
  console.log('\n' + '─'.repeat(55) + '\n');
}

main().catch(e => {
  console.error('\n❌  Unexpected error:', e.message);
  process.exit(1);
});
