/* ═══════════════════════════════════════════════════════════
   PRINTDROP — DESIGNS LIBRARY (520+ designs)
   All strings use double-quotes. No apostrophes in values.
   items[] lists compatible product IDs from catalog.js
═══════════════════════════════════════════════════════════ */

const ALL = ["tee","hoodie","longsleeve","croptee","tanktop","raglan",
  "sweatpants","snapback","dadhut","beanie","bucket_hat","tote_bag",
  "drawstring","fanny_pack","mug","travel_mug","water_bottle","pillow",
  "poster","socks","face_mask","apron","phone_case","laptop_sleeve",
  "mousepad","notebook","sticker_sheet","greeting_card"];
const AP  = ["tee","hoodie","longsleeve","croptee","tanktop","raglan","sweatpants"];
const HAT = ["snapback","dadhut","beanie","bucket_hat","trucker_hat"];
const MUG = ["mug","travel_mug","water_bottle"];
const FLAT= ["tote_bag","pillow","poster","mousepad","notebook","sticker_sheet"];

const DESIGNS = [
  {id:"g01",cat:"gym",name:"No Days Off",text:"NO DAYS\nOFF",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#ffffff",bg:"#111111", badge:"Bestseller",items:AP},
  {id:"g02",cat:"gym",name:"Built Different",text:"BUILT\nDIFFERENT",font:"'Bebas Neue',sans-serif",fs:"2.1rem",tc:"#f39c12",bg:"#1a1a2e",items:AP},
  {id:"g03",cat:"gym",name:"Pain Is Progress",text:"PAIN IS\nPROGRESS",font:"'Russo One',sans-serif",fs:"1.8rem",tc:"#ef4444",bg:"#f9f8f5",items:AP},
  {id:"g04",cat:"gym",name:"Beast Mode",text:"BEAST\nMODE",font:"'Graduate',cursive",fs:"2rem",tc:"#ff6b35",bg:"#1a1a1a",items:AP},
  {id:"g05",cat:"gym",name:"Earn It Every Day",text:"EARN IT\nEVERY DAY",font:"'Anton',sans-serif",fs:"1.9rem",tc:"#ffffff",bg:"#c0392b", badge:"Hot",items:AP},
  {id:"g06",cat:"gym",name:"One More Rep",text:"ONE MORE\nREP",font:"'Teko',sans-serif",fs:"2.8rem",tc:"#ffffff",bg:"#2d2d44",items:AP},
  {id:"g07",cat:"gym",name:"Train Insane",text:"TRAIN\nINSANE",font:"'Black Han Sans',sans-serif",fs:"2rem",tc:"#fbbf24",bg:"#111111",items:AP},
  {id:"g08",cat:"gym",name:"No Excuses",text:"NO\nEXCUSES",font:"'Ultra',serif",fs:"2.4rem",tc:"#ef4444",bg:"#f9f8f5",items:AP},
  {id:"g09",cat:"gym",name:"Gains Season",text:"GAINS\nSEASON",font:"'Bungee',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#16a34a",items:AP},
  {id:"g10",cat:"gym",name:"Gym Rat",text:"GYM\nRAT",font:"'Bebas Neue',sans-serif",fs:"3rem",tc:"#ffffff",bg:"#1d3461",items:AP},
  {id:"g11",cat:"gym",name:"Sweat Is Fat Crying",text:"SWEAT IS\nFAT CRYING",font:"'Anton',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#b91c1c",items:AP},
  {id:"g12",cat:"gym",name:"Lift Heavy Eat Big",text:"LIFT HEAVY\nEAT BIG",font:"'Graduate',cursive",fs:"1.6rem",tc:"#fbbf24",bg:"#1f2937",items:AP},
  {id:"g13",cat:"gym",name:"Cardio Is Hardio",text:"CARDIO\nIS HARDIO",font:"'Permanent Marker',cursive",fs:"1.4rem",tc:"#000000",bg:"#fde047",items:AP},
  {id:"g14",cat:"gym",name:"Lift Bro",text:"LIFT BRO",font:"'Anton',sans-serif",fs:"2.5rem",tc:"#ffffff",bg:"#7c3aed",items:AP},
  {id:"g15",cat:"gym",name:"Rep After Rep",text:"REP\nAFTER REP",font:"'Oswald',sans-serif",fs:"2.2rem",tc:"#ffffff",bg:"#0f172a",items:AP},
  {id:"g16",cat:"gym",name:"Swole Patrol",text:"SWOLE\nPATROL",font:"'Bungee',cursive",fs:"1.9rem",tc:"#22c55e",bg:"#0f172a",items:AP},
  {id:"g17",cat:"gym",name:"Plates Before Dates",text:"PLATES\nBEFORE DATES",font:"'Anton',sans-serif",fs:"1.7rem",tc:"#ffffff",bg:"#111111",items:AP},
  {id:"g18",cat:"gym",name:"Squat For Food",text:"WILL SQUAT\nFOR FOOD",font:"'Graduate',cursive",fs:"1.5rem",tc:"#fbbf24",bg:"#1a1a2e",items:AP},
  {id:"g19",cat:"gym",name:"Protein And Progress",text:"PROTEIN\n& PROGRESS",font:"'Bebas Neue',sans-serif",fs:"2rem",tc:"#22c55e",bg:"#111111",items:AP},
  {id:"g20",cat:"gym",name:"Built Not Born",text:"BUILT\nNOT BORN",font:"'Russo One',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#7c2d12",items:AP},
  {id:"g21",cat:"gym",name:"The Grind Is Real",text:"THE GRIND\nIS REAL",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#f97316",bg:"#0f172a",items:AP},
  {id:"g22",cat:"gym",name:"Suns Out Guns Out",text:"SUNS OUT\nGUNS OUT",font:"'Bungee',cursive",fs:"1.6rem",tc:"#000000",bg:"#fde047",items:AP},
  {id:"g23",cat:"gym",name:"Iron Sharpens Iron",text:"IRON\nSHARPENS IRON",font:"'Playfair Display',serif",fs:"1.6rem",tc:"#ffffff",bg:"#292524",items:AP},
  {id:"g24",cat:"gym",name:"Run The Day",text:"RUN\nTHE DAY",font:"'Graduate',cursive",fs:"2.2rem",tc:"#60a5fa",bg:"#0f172a",items:AP},
  {id:"g25",cat:"gym",name:"Zero Excuses",text:"ZERO\nEXCUSES",font:"'Anton',sans-serif",fs:"2.5rem",tc:"#ef4444",bg:"#000000",items:AP},
  {id:"g26",cat:"gym",name:"Strong Is Beautiful",text:"STRONG IS\nBEAUTIFUL",font:"'Dancing Script',cursive",fs:"1.8rem",tc:"#f9a8d4",bg:"#4a044e",items:AP},
  {id:"g27",cat:"gym",name:"No Pain No Gain",text:"NO PAIN\nNO GAIN",font:"'Bebas Neue',sans-serif",fs:"2.4rem",tc:"#ffffff",bg:"#c0392b",items:AP},
  {id:"g28",cat:"gym",name:"Gym Membership Paid",text:"GYM MEMBERSHIP\nPAID\nNOW GO",font:"'Caveat',cursive",fs:"1.1rem",tc:"#000000",bg:"#fde047",items:AP},
  {id:"g29",cat:"gym",name:"Eat Sleep Lift",text:"EAT\nSLEEP\nLIFT\nREPEAT",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#ffffff",bg:"#111111",items:AP},
  {id:"g30",cat:"gym",name:"Thick Thighs",text:"THICK THIGHS\nSAVE LIVES",font:"'Bungee',cursive",fs:"1.4rem",tc:"#ffffff",bg:"#831843",items:AP},
  {id:"g31",cat:"gym",name:"Mental Workout",text:"THE REAL\nWORKOUT IS\nMENTAL",font:"'Playfair Display',serif",fs:"1.3rem",tc:"#ffffff",bg:"#1e3a5f",items:AP},
  {id:"g32",cat:"gym",name:"Fitness Is Therapy",text:"FITNESS IS\nMY THERAPY",font:"'Russo One',sans-serif",fs:"1.7rem",tc:"#22c55e",bg:"#0f172a",items:AP},
  {id:"g33",cat:"gym",name:"Deadlifts Deep Talks",text:"DEADLIFTS\n& DEEP TALKS",font:"'Graduate',cursive",fs:"1.4rem",tc:"#fbbf24",bg:"#111827",items:AP},
  {id:"g34",cat:"gym",name:"5AM Morning Crew",text:"5AM\nMORNING\nCREW",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#1e3a5f",items:AP},
  {id:"g35",cat:"gym",name:"Fueled By Pre-Workout",text:"FUELED BY\nPRE-WORKOUT",font:"'Bungee',cursive",fs:"1.5rem",tc:"#22c55e",bg:"#0f172a",items:AP},
  {id:"g36",cat:"gym",name:"Chest Day Every Day",text:"CHEST DAY\nEVERY DAY",font:"'Anton',sans-serif",fs:"1.9rem",tc:"#ffffff",bg:"#111111",items:AP},
  {id:"g37",cat:"gym",name:"Marathon Mode",text:"MARATHON\nMODE: ON",font:"'Bebas Neue',sans-serif",fs:"2.2rem",tc:"#3b82f6",bg:"#0f172a",items:AP},
  {id:"g38",cat:"gym",name:"Lift Like A Mother",text:"LIFT LIKE\nA MOTHER",font:"'Graduate',cursive",fs:"1.8rem",tc:"#f9a8d4",bg:"#1a1a2e",items:AP},
  {id:"g39",cat:"gym",name:"Powerlifter",text:"POWER\nLIFTER",font:"'Ultra',serif",fs:"2.4rem",tc:"#ffffff",bg:"#7c2d12",items:AP},
  {id:"g40",cat:"gym",name:"Gains Goblin",text:"GAINS\nGOBLIN",font:"'Bungee',cursive",fs:"1.8rem",tc:"#22c55e",bg:"#0f172a",items:AP},

  {id:"m01",cat:"motivational",name:"Dream It Build It",text:"DREAM IT\nBUILD IT",font:"'Plus Jakarta Sans',sans-serif",fs:"1.8rem",tc:"#ffffff",bg:"#0a0a0a", badge:"Popular",items:[...AP,...FLAT]},
  {id:"m02",cat:"motivational",name:"Rise And Grind",text:"RISE\n& GRIND",font:"'Anton',sans-serif",fs:"2.5rem",tc:"#f39c12",bg:"#1d3461",items:[...AP,...FLAT]},
  {id:"m03",cat:"motivational",name:"Relentless",text:"RELENTLESS",font:"'Bebas Neue',sans-serif",fs:"2.6rem",tc:"#ffffff",bg:"#c0392b",items:[...AP,...FLAT]},
  {id:"m04",cat:"motivational",name:"Be The Storm",text:"BE THE\nSTORM",font:"'Russo One',sans-serif",fs:"2rem",tc:"#60a5fa",bg:"#111827",items:[...AP,...FLAT]},
  {id:"m05",cat:"motivational",name:"Start Now",text:"START\nNOW.",font:"'Anton',sans-serif",fs:"2.5rem",tc:"#000000",bg:"#fde047",items:[...AP,...FLAT]},
  {id:"m06",cat:"motivational",name:"Unstoppable",text:"UNSTOPPABLE",font:"'Bebas Neue',sans-serif",fs:"1.8rem",tc:"#ffffff",bg:"#dc2626",items:[...AP,...FLAT]},
  {id:"m07",cat:"motivational",name:"Grind And Shine",text:"GRIND\n& SHINE",font:"'Graduate',cursive",fs:"2rem",tc:"#f59e0b",bg:"#1f2937",items:[...AP,...FLAT]},
  {id:"m08",cat:"motivational",name:"Keep Going",text:"KEEP\nGOING.",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#ffffff",bg:"#374151",items:[...AP,...FLAT]},
  {id:"m09",cat:"motivational",name:"Do Hard Things",text:"DO HARD\nTHINGS",font:"'Bungee',cursive",fs:"1.7rem",tc:"#ffffff",bg:"#7f1d1d",items:[...AP,...FLAT]},
  {id:"m10",cat:"motivational",name:"Prove Them Wrong",text:"PROVE\nTHEM WRONG",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#ef4444",bg:"#000000",items:[...AP,...FLAT]},
  {id:"m11",cat:"motivational",name:"Make It Happen",text:"MAKE IT\nHAPPEN",font:"'Oswald',sans-serif",fs:"2.2rem",tc:"#ffffff",bg:"#4f46e5",items:[...AP,...FLAT]},
  {id:"m12",cat:"motivational",name:"Your Only Limit",text:"YOUR ONLY\nLIMIT IS YOU",font:"'Black Han Sans',sans-serif",fs:"1.2rem",tc:"#ffffff",bg:"#064e3b",items:[...AP,...FLAT]},
  {id:"m13",cat:"motivational",name:"Outwork Everyone",text:"OUTWORK\nEVERYONE",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#111111",items:[...AP,...FLAT]},
  {id:"m14",cat:"motivational",name:"Trust The Process",text:"TRUST\nTHE PROCESS",font:"'Lobster',cursive",fs:"1.8rem",tc:"#fbbf24",bg:"#1a1a2e",items:[...AP,...FLAT]},
  {id:"m15",cat:"motivational",name:"Chase Excellence",text:"CHASE\nEXCELLENCE",font:"'Bebas Neue',sans-serif",fs:"2.5rem",tc:"#ffffff",bg:"#0c4a6e",items:[...AP,...FLAT]},
  {id:"m16",cat:"motivational",name:"Built For More",text:"BUILT\nFOR MORE",font:"'Russo One',sans-serif",fs:"2.1rem",tc:"#ffffff",bg:"#7c2d12",items:[...AP,...FLAT]},
  {id:"m17",cat:"motivational",name:"One Percent Better",text:"1%\nBETTER\nEVERY DAY",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#0f172a",items:[...AP,...FLAT]},
  {id:"m18",cat:"motivational",name:"Legacy Over Labels",text:"LEGACY\nOVER LABELS",font:"'Playfair Display',serif",fs:"1.7rem",tc:"#ffffff",bg:"#1c1917",items:[...AP,...FLAT]},
  {id:"m19",cat:"motivational",name:"Actions Over Words",text:"ACTIONS\nOVER WORDS",font:"'Graduate',cursive",fs:"1.8rem",tc:"#f59e0b",bg:"#111111",items:[...AP,...FLAT]},
  {id:"m20",cat:"motivational",name:"Resilient",text:"RESILIENT",font:"'Bebas Neue',sans-serif",fs:"3rem",tc:"#3b82f6",bg:"#0f172a",items:[...AP,...FLAT]},
  {id:"m21",cat:"motivational",name:"Eyes On The Prize",text:"EYES ON\nTHE PRIZE",font:"'Anton',sans-serif",fs:"2rem",tc:"#fbbf24",bg:"#1a1a2e",items:[...AP,...FLAT]},
  {id:"m22",cat:"motivational",name:"Win The Morning",text:"WIN THE\nMORNING",font:"'Bungee',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#111111",items:[...AP,...FLAT]},
  {id:"m23",cat:"motivational",name:"Progress Not Perfection",text:"PROGRESS\nNOT\nPERFECTION",font:"'Oswald',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#1e3a5f",items:[...AP,...FLAT]},
  {id:"m24",cat:"motivational",name:"Hungry For More",text:"HUNGRY\nFOR MORE",font:"'Graduate',cursive",fs:"2rem",tc:"#f97316",bg:"#0f172a",items:[...AP,...FLAT]},
  {id:"m25",cat:"motivational",name:"No Shortcuts",text:"NO\nSHORTCUTS",font:"'Anton',sans-serif",fs:"2.4rem",tc:"#ffffff",bg:"#b91c1c",items:[...AP,...FLAT]},
  {id:"m26",cat:"motivational",name:"Vision Board Energy",text:"VISION\nBOARD\nENERGY",font:"'Dancing Script',cursive",fs:"1.6rem",tc:"#f9a8d4",bg:"#4a044e",items:[...AP,...FLAT]},
  {id:"m27",cat:"motivational",name:"Pressure Makes Diamonds",text:"PRESSURE\nMAKES\nDIAMONDS",font:"'Russo One',sans-serif",fs:"1.3rem",tc:"#c084fc",bg:"#1e1b4b",items:[...AP,...FLAT]},
  {id:"m28",cat:"motivational",name:"Become Unbreakable",text:"BECOME\nUNBREAKABLE",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#ffffff",bg:"#0a0a0a",items:[...AP,...FLAT]},
  {id:"m29",cat:"motivational",name:"Built Different Era",text:"IN MY\nBUILT DIFFERENT\nERA",font:"'Plus Jakarta Sans',sans-serif",fs:"1.2rem",tc:"#ffffff",bg:"#111111",items:[...AP,...FLAT]},
  {id:"m30",cat:"motivational",name:"Today Not Tomorrow",text:"TODAY.\nNOT\nTOMORROW.",font:"'Bebas Neue',sans-serif",fs:"2.2rem",tc:"#f97316",bg:"#0f172a",items:[...AP,...FLAT]},
  {id:"p01",cat:"puns",name:"I Am Nacho Average",text:"I AM\nNACHO AVERAGE",font:"'Bungee',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#d97706", badge:"Fan Fav",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p02",cat:"puns",name:"Resting Beach Face",text:"RESTING\nBEACH FACE",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#0ea5e9",bg:"#f0f9ff",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p03",cat:"puns",name:"Shell Yeah",text:"SHELL\nYEAH",font:"'Graduate',cursive",fs:"2rem",tc:"#ffffff",bg:"#0369a1",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p04",cat:"puns",name:"Kale Yeah",text:"KALE\nYEAH",font:"'Russo One',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#166534",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p05",cat:"puns",name:"Namaste In Bed",text:"NAMASTE\nIN BED",font:"'Dancing Script',cursive",fs:"1.9rem",tc:"#7c3aed",bg:"#faf5ff",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p06",cat:"puns",name:"I Donut Care",text:"I DONUT\nCARE",font:"'Bungee',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#db2777",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p07",cat:"puns",name:"Cereal Killer",text:"CEREAL\nKILLER",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#111111",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p08",cat:"puns",name:"Avo Good Day",text:"AVO GOOD\nDAY",font:"'Pacifico',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#15803d",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p09",cat:"puns",name:"Feeling Grape",text:"FEELING\nGRAPE",font:"'Graduate',cursive",fs:"2rem",tc:"#ffffff",bg:"#7c3aed",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p10",cat:"puns",name:"Aloe You Vera Much",text:"ALOE YOU\nVERA MUCH",font:"'Lobster',cursive",fs:"1.4rem",tc:"#ffffff",bg:"#15803d",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p11",cat:"puns",name:"Tea-riffic",text:"TEA-RIFFIC",font:"'Pacifico',cursive",fs:"1.8rem",tc:"#92400e",bg:"#fef3c7",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p12",cat:"puns",name:"Pho Real Tho",text:"PHO\nREAL THO",font:"'Bebas Neue',sans-serif",fs:"2.5rem",tc:"#ffffff",bg:"#7c2d12",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p13",cat:"puns",name:"I Work Out Of Bed",text:"I WORK OUT\nOUT OF BED",font:"'Anton',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#0f172a",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p14",cat:"puns",name:"Unamused And Confused",text:"UNAMUSED\n& CONFUSED",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#000000",bg:"#e2e8f0",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p15",cat:"puns",name:"Wine Not",text:"WINE\nNOT",font:"'Lobster',cursive",fs:"2rem",tc:"#ffffff",bg:"#7c2d12",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p16",cat:"puns",name:"Brew-tiful Morning",text:"BREW-TIFUL\nMORNING",font:"'Pacifico',cursive",fs:"1.5rem",tc:"#92400e",bg:"#fff7ed",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p17",cat:"puns",name:"Espresso Yourself",text:"ESPRESSO\nYOURSELF",font:"'Bungee',cursive",fs:"1.7rem",tc:"#ffffff",bg:"#6f4e37",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p18",cat:"puns",name:"Gouda Vibes Only",text:"GOUDA\nVIBES ONLY",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#000000",bg:"#fde047",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p19",cat:"puns",name:"Im On A Roll",text:"IM ON\nA ROLL",font:"'Caveat',cursive",fs:"1.8rem",tc:"#92400e",bg:"#fef3c7",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p20",cat:"puns",name:"Clam Down",text:"CLAM\nDOWN",font:"'Graduate',cursive",fs:"2rem",tc:"#ffffff",bg:"#0369a1",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p21",cat:"puns",name:"You Batter Believe It",text:"YOU BATTER\nBELIEVE IT",font:"'Anton',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#1d3461",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p22",cat:"puns",name:"I Believe In Leaf",text:"I BELIEVE\nIN LEAF",font:"'Dancing Script',cursive",fs:"1.8rem",tc:"#166534",bg:"#f0fdf4",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p23",cat:"puns",name:"Holy Guac",text:"HOLY\nGUAC",font:"'Bungee',cursive",fs:"2rem",tc:"#ffffff",bg:"#15803d",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p24",cat:"puns",name:"Beet It",text:"BEET IT",font:"'Anton',sans-serif",fs:"2.5rem",tc:"#ffffff",bg:"#881337",items:[...AP,...FLAT,"apron","mug"]},
  {id:"p25",cat:"puns",name:"Lettuce Celebrate",text:"LETTUCE\nCELEBRATE",font:"'Pacifico',cursive",fs:"1.4rem",tc:"#166534",bg:"#f0fdf4",items:[...AP,...FLAT,"apron","mug"]},

  {id:"dj01",cat:"dadjokes",name:"Time To Get Crackin",text:"TIME TO GET\nCRACKIN",font:"'Bungee',cursive",fs:"1.4rem",tc:"#000000",bg:"#fde047", badge:"Best Dad",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj02",cat:"dadjokes",name:"I Knead You",text:"I KNEAD\nYOU",font:"'Lobster',cursive",fs:"2rem",tc:"#ffffff",bg:"#92400e",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj03",cat:"dadjokes",name:"Dad Bod Loading",text:"DAD BOD\nLOADING 70%",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#000000",bg:"#e2e8f0",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj04",cat:"dadjokes",name:"Grill Sergeant",text:"GRILL\nSERGEANT",font:"'Anton',sans-serif",fs:"2.1rem",tc:"#ffffff",bg:"#92400e",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj05",cat:"dadjokes",name:"Will Work For WiFi",text:"WILL WORK\nFOR Wi-Fi",font:"'Russo One',sans-serif",fs:"1.7rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj06",cat:"dadjokes",name:"Too Punny",text:"I AM\nTOO PUNNY\nfor this shirt",font:"'Pacifico',cursive",fs:"1.2rem",tc:"#ffffff",bg:"#7c3aed",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj07",cat:"dadjokes",name:"Worlds Okayest Dad",text:"WORLDS\nOKAYEST DAD",font:"'Anton',sans-serif",fs:"1.9rem",tc:"#ffffff",bg:"#374151",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj08",cat:"dadjokes",name:"Heart Led To Fridge",text:"I FOLLOWED\nMY HEART\nTO THE FRIDGE",font:"'Caveat',cursive",fs:"1.1rem",tc:"#000000",bg:"#fff7ed",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj09",cat:"dadjokes",name:"Cereal Offender",text:"CEREAL\nOFFENDER",font:"'Graduate',cursive",fs:"1.9rem",tc:"#ffffff",bg:"#1e3a5f",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj10",cat:"dadjokes",name:"Level 40 Unlocked",text:"LEVEL 40\nUNLOCKED",font:"'Space Mono',monospace",fs:"1.2rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj11",cat:"dadjokes",name:"Free Dad Hugs",text:"FREE\nDAD HUGS",font:"'Bungee',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#16a34a",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj12",cat:"dadjokes",name:"Nacho Problem",text:"NACHO\nPROBLEM",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#d97706",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj13",cat:"dadjokes",name:"Dad Joke Loading",text:"DAD JOKE\nLOADING\nplease wait",font:"'Space Mono',monospace",fs:"1rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj14",cat:"dadjokes",name:"Energy Saving Mode",text:"NOT LAZY\nIN ENERGY\nSAVING MODE",font:"'Caveat',cursive",fs:"1.1rem",tc:"#000000",bg:"#fde047",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj15",cat:"dadjokes",name:"Professional Plant Killer",text:"PROFESSIONAL\nPLANT KILLER",font:"'Bungee',cursive",fs:"1.4rem",tc:"#ffffff",bg:"#15803d",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj16",cat:"dadjokes",name:"BBQ Master",text:"BBQ\nMASTER",font:"'Graduate',cursive",fs:"2.4rem",tc:"#f97316",bg:"#1a1a1a",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj17",cat:"dadjokes",name:"Side Effects Dad Jokes",text:"SIDE EFFECTS\nMAY INCLUDE\nDAD JOKES",font:"'Space Mono',monospace",fs:"0.9rem",tc:"#000000",bg:"#e2e8f0",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj18",cat:"dadjokes",name:"Taco Bout Amazing",text:"TACO BOUT\nAMAZING",font:"'Bungee',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#b45309",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj19",cat:"dadjokes",name:"Coffee And Chaos",text:"I RUN ON\nCOFFEE\n& CHAOS",font:"'Anton',sans-serif",fs:"1.6rem",tc:"#ffffff",bg:"#6f4e37",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj20",cat:"dadjokes",name:"Trophy Husband",text:"TROPHY\nHUSBAND",font:"'Anton',sans-serif",fs:"2rem",tc:"#fbbf24",bg:"#111111",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj21",cat:"dadjokes",name:"Pitcher Perfect",text:"PITCHER\nPERFECT",font:"'Graduate',cursive",fs:"1.9rem",tc:"#fbbf24",bg:"#1a1a2e",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj22",cat:"dadjokes",name:"Zero To Dad",text:"ZERO TO DAD\nIN 9 MONTHS",font:"'Space Mono',monospace",fs:"0.95rem",tc:"#000000",bg:"#f0f9ff",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj23",cat:"dadjokes",name:"Mullet Mentality",text:"BUSINESS\nIN FRONT\nPARTY BACK",font:"'Anton',sans-serif",fs:"1.7rem",tc:"#fbbf24",bg:"#0f172a",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj24",cat:"dadjokes",name:"According To Google",text:"ACCORDING TO\nMY RESEARCH\n(I Googled it)",font:"'Caveat',cursive",fs:"0.95rem",tc:"#000000",bg:"#f1f5f9",items:[...AP,"apron","mug","greeting_card"]},
  {id:"dj25",cat:"dadjokes",name:"Officially Old",text:"OFFICIALLY\nOLD\n& LOVING IT",font:"'Lobster',cursive",fs:"1.5rem",tc:"#fbbf24",bg:"#1c1917",items:[...AP,"apron","mug","greeting_card"]},

  {id:"t01",cat:"teen",name:"Understood The Assignment",text:"UNDERSTOOD\nTHE ASSIGNMENT",font:"'Anton',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#7c3aed", badge:"Trending",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t02",cat:"teen",name:"Slay",text:"SLAY +",font:"'Bebas Neue',sans-serif",fs:"3.5rem",tc:"#f0abfc",bg:"#4a044e",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t03",cat:"teen",name:"No Cap",text:"NO CAP\nFR FR",font:"'Bungee',cursive",fs:"2rem",tc:"#ffffff",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t04",cat:"teen",name:"Delulu Is The Solulu",text:"DELULU IS\nTHE SOLULU",font:"'Anton',sans-serif",fs:"1.7rem",tc:"#f9a8d4",bg:"#500724",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t05",cat:"teen",name:"Touch Grass",text:"TOUCH\nGRASS",font:"'Graduate',cursive",fs:"2rem",tc:"#ffffff",bg:"#166534",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t06",cat:"teen",name:"Unhinged Era",text:"UNHINGED\nERA",font:"'Bungee',cursive",fs:"1.8rem",tc:"#fbbf24",bg:"#111111",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t07",cat:"teen",name:"Main Character",text:"MAIN\nCHARACTER",font:"'Anton',sans-serif",fs:"1.9rem",tc:"#ffffff",bg:"#831843",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t08",cat:"teen",name:"Vibe Check Passed",text:"VIBE\nCHECK +",font:"'Russo One',sans-serif",fs:"2.2rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t09",cat:"teen",name:"Ate And Left No Crumbs",text:"ATE AND LEFT\nNO CRUMBS",font:"'Plus Jakarta Sans',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#dc2626",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t10",cat:"teen",name:"Low Key Unwell",text:"LOW KEY\nUNWELL",font:"'Caveat',cursive",fs:"2rem",tc:"#000000",bg:"#e0f2fe",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t11",cat:"teen",name:"In My Growth Era",text:"IN MY\nGROWTH ERA",font:"'Pacifico',cursive",fs:"1.5rem",tc:"#f9a8d4",bg:"#4a044e",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t12",cat:"teen",name:"That Girl Era",text:"THAT\nGIRL ERA",font:"'Dancing Script',cursive",fs:"2.5rem",tc:"#ffffff",bg:"#0f4c3a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t13",cat:"teen",name:"NPC Mode",text:"NPC\nMODE: ON",font:"'Space Mono',monospace",fs:"1.4rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t14",cat:"teen",name:"Rizz Energy",text:"RIZZ\nENERGY",font:"'Bebas Neue',sans-serif",fs:"2.8rem",tc:"#fbbf24",bg:"#1a1a2e",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t15",cat:"teen",name:"Hyper Independent",text:"HYPER\nINDEPENDENT",font:"'Space Mono',monospace",fs:"1rem",tc:"#dc2626",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t16",cat:"teen",name:"Rent Free",text:"LIVING\nRENT FREE\nin my head",font:"'Caveat',cursive",fs:"1.3rem",tc:"#000000",bg:"#fef3c7",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t17",cat:"teen",name:"POV You Are Me",text:"POV:\nYOU ARE ME\nAND IT SUCKS",font:"'Space Mono',monospace",fs:"0.95rem",tc:"#000000",bg:"#f1f5f9",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t18",cat:"teen",name:"Brat Summer",text:"BRAT\nSUMMER",font:"'Anton',sans-serif",fs:"2.5rem",tc:"#000000",bg:"#84cc16",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t19",cat:"teen",name:"Serve",text:"SERVE +",font:"'Bebas Neue',sans-serif",fs:"3.5rem",tc:"#f9a8d4",bg:"#111111",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t20",cat:"teen",name:"Not Okay But Okay",text:"NOT OKAY\nBUT OKAY LOL",font:"'Caveat',cursive",fs:"1.3rem",tc:"#000000",bg:"#fce7f3",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t21",cat:"teen",name:"The Ick",text:"the ick.",font:"'Space Mono',monospace",fs:"1.8rem",tc:"#000000",bg:"#f1f5f9",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t22",cat:"teen",name:"Villain Era",text:"IN MY\nVILLAIN ERA",font:"'Bungee',cursive",fs:"1.7rem",tc:"#ef4444",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t23",cat:"teen",name:"Soft Era",text:"IN MY\nSOFT ERA",font:"'Dancing Script',cursive",fs:"2rem",tc:"#f9a8d4",bg:"#fce7f3",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t24",cat:"teen",name:"Rotting Season",text:"ROTTING\nSEASON",font:"'Anton',sans-serif",fs:"2rem",tc:"#e0f2fe",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t25",cat:"teen",name:"Goblin Mode",text:"GOBLIN\nMODE:\nACTIVATED",font:"'Graduate',cursive",fs:"1.5rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t26",cat:"teen",name:"Loud Budgeting Era",text:"LOUD\nBUDGETING\nERA",font:"'Space Mono',monospace",fs:"1rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t27",cat:"teen",name:"De-influencing",text:"DE-\nINFLUENCING",font:"'Bebas Neue',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#374151",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t28",cat:"teen",name:"Aesthetic",text:"AESTHETIC +",font:"'Plus Jakarta Sans',sans-serif",fs:"1.5rem",tc:"#f9a8d4",bg:"#4a044e",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t29",cat:"teen",name:"I Am The Drama",text:"I AM\nTHE DRAMA",font:"'Anton',sans-serif",fs:"2rem",tc:"#f97316",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t30",cat:"teen",name:"In My Therapy Era",text:"IN MY\nTHERAPY\nERA",font:"'Caveat',cursive",fs:"1.3rem",tc:"#000000",bg:"#fef3c7",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t31",cat:"teen",name:"Y2K Baby",text:"Y2K\nBABY",font:"'Bungee',cursive",fs:"2rem",tc:"#c084fc",bg:"#1e1b4b",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t32",cat:"teen",name:"Chronically Online",text:"CHRONICALLY\nONLINE",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#22c55e",bg:"#0f172a", badge:"100% Real",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t33",cat:"teen",name:"Beige Flag",text:"BEIGE\nFLAG",font:"'Plus Jakarta Sans',sans-serif",fs:"1.8rem",tc:"#92400e",bg:"#fef3c7",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t34",cat:"teen",name:"Situationship Survivor",text:"SITUATION-\nSHIP\nSURVIVOR",font:"'Anton',sans-serif",fs:"1.6rem",tc:"#f9a8d4",bg:"#500724",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t35",cat:"teen",name:"Lore Dump",text:"SKIP SMALL\nTALK\nLORE DUMP",font:"'Space Mono',monospace",fs:"0.9rem",tc:"#000000",bg:"#f1f5f9",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t36",cat:"teen",name:"Ate That No Receipt",text:"ATE THAT\nNO RECEIPT",font:"'Bungee',cursive",fs:"1.5rem",tc:"#ffffff",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t37",cat:"teen",name:"Side Quest",text:"ON A\nSIDE QUEST",font:"'Graduate',cursive",fs:"1.8rem",tc:"#fbbf24",bg:"#111827",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t38",cat:"teen",name:"Coquette Era",text:"COQUETTE\nERA",font:"'Dancing Script',cursive",fs:"2rem",tc:"#f9a8d4",bg:"#fce7f3",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t39",cat:"teen",name:"Neon Sign Personality",text:"NEON SIGN\nPERSONALITY",font:"'Bungee',cursive",fs:"1.3rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"t40",cat:"teen",name:"Sigma Grindset",text:"SIGMA\nGRINDSET",font:"'Anton',sans-serif",fs:"2rem",tc:"#fbbf24",bg:"#111111",items:[...AP,...HAT,"tote_bag","phone_case","notebook"]},
  {id:"c01",cat:"culture",name:"Algorithm Made Me",text:"THE ALGORITHM\nMADE ME\nBUY THIS",font:"'Caveat',cursive",fs:"1.3rem",tc:"#000000",bg:"#fde047",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c02",cat:"culture",name:"Out Of Office Forever",text:"OUT OF\nOFFICE\nFOREVER",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#ffffff",bg:"#1d3461",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c03",cat:"culture",name:"Protect Your Peace",text:"PROTECT\nYOUR PEACE",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#ffffff",bg:"#1e3a5f",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c04",cat:"culture",name:"Doomscrolling Champion",text:"DOOMSCROLLING\nCHAMPION",font:"'Anton',sans-serif",fs:"1.4rem",tc:"#ffffff",bg:"#111111",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c05",cat:"culture",name:"Quiet Quitting Pro",text:"QUIET\nQUITTING\nPRO",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c06",cat:"culture",name:"Unbothered Moisturized",text:"UNBOTHERED\n& MOISTURIZED",font:"'Anton',sans-serif",fs:"1.6rem",tc:"#f9a8d4",bg:"#4a044e",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c07",cat:"culture",name:"We Ball",text:"WE\nBALL",font:"'Bebas Neue',sans-serif",fs:"3.5rem",tc:"#f97316",bg:"#111111",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c08",cat:"culture",name:"Barista Is My Therapist",text:"MY BARISTA\nIS MY\nTHERAPIST",font:"'Bungee',cursive",fs:"1.2rem",tc:"#ffffff",bg:"#6f4e37",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c09",cat:"culture",name:"Soft Life Only",text:"SOFT\nLIFE ONLY",font:"'Dancing Script',cursive",fs:"2.2rem",tc:"#f9a8d4",bg:"#4a044e",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c10",cat:"culture",name:"Setting Boundaries 2020",text:"SETTING\nBOUNDARIES\nSINCE 2020",font:"'Roboto Condensed',sans-serif",fs:"1.2rem",tc:"#ffffff",bg:"#374151",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c11",cat:"culture",name:"AI Cannot Replace This",text:"AI CANNOT\nREPLACE THIS\n(yet)",font:"'Space Mono',monospace",fs:"1rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c12",cat:"culture",name:"Bed Rotting Pro",text:"PROFESSIONAL\nBED ROTTER",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#e0f2fe",bg:"#0f172a",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c13",cat:"culture",name:"WFH Champion",text:"WFH\nCHAMPION",font:"'Graduate',cursive",fs:"1.9rem",tc:"#fbbf24",bg:"#0f172a",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c14",cat:"culture",name:"Do Not Disturb",text:"DO NOT\nDISTURB",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#111111",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c15",cat:"culture",name:"Introvert Recharging",text:"INTROVERT\nRECHARGING",font:"'Space Mono',monospace",fs:"0.9rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c16",cat:"culture",name:"Touch Grass Daily",text:"TOUCH GRASS\nDAILY",font:"'Graduate',cursive",fs:"2rem",tc:"#ffffff",bg:"#166534",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c17",cat:"culture",name:"Normalize Rest",text:"NORMALIZE\nREST",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#ffffff",bg:"#1e3a5f",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c18",cat:"culture",name:"Anti-Hustle Culture",text:"ANTI\nHUSTLE\nCULTURE",font:"'Anton',sans-serif",fs:"1.9rem",tc:"#ef4444",bg:"#0f172a",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c19",cat:"culture",name:"Delete My Data",text:"DELETE\nMY DATA\nPLEASE",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c20",cat:"culture",name:"Micro-Nap Enthusiast",text:"MICRO-NAP\nENTHUSIAST",font:"'Bungee',cursive",fs:"1.6rem",tc:"#e0f2fe",bg:"#1e3a5f",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c21",cat:"culture",name:"Capitalism Made Me",text:"CAPITALISM\nMADE ME\nBUY THIS",font:"'Space Mono',monospace",fs:"1rem",tc:"#000000",bg:"#fde047",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c22",cat:"culture",name:"Anxious But Fashionable",text:"ANXIOUS\nBUT MAKE IT\nFASHION",font:"'Plus Jakarta Sans',sans-serif",fs:"1.1rem",tc:"#ffffff",bg:"#500724",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c23",cat:"culture",name:"According To TikTok",text:"ACCORDING\nTO TIKTOK",font:"'Caveat',cursive",fs:"1.8rem",tc:"#000000",bg:"#fde047",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c24",cat:"culture",name:"Hot Girl Walk",text:"HOT GIRL\nWALK",font:"'Anton',sans-serif",fs:"2rem",tc:"#f9a8d4",bg:"#500724",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},
  {id:"c25",cat:"culture",name:"Climate Anxiety Fashion",text:"CLIMATE\nANXIETY\nBUT MAKE IT FUN",font:"'Space Mono',monospace",fs:"0.85rem",tc:"#ffffff",bg:"#166534",items:[...AP,"tote_bag","mug","pillow","poster","phone_case","mousepad"]},

  {id:"f01",cat:"faith",name:"Faith Over Fear",text:"FAITH\nOVER FEAR",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#ffffff",bg:"#2c3e50", badge:"Bestseller",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f02",cat:"faith",name:"Gods Got This",text:"GODS\nGOT THIS",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#f39c12",bg:"#ffffff",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f03",cat:"faith",name:"Blessed And Grateful",text:"BLESSED\n& GRATEFUL",font:"'Pacifico',cursive",fs:"1.4rem",tc:"#8e44ad",bg:"#faf5ff",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f04",cat:"faith",name:"Walk By Faith",text:"WALK\nBY FAITH",font:"'Lobster',cursive",fs:"2rem",tc:"#ffffff",bg:"#8e44ad",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f05",cat:"faith",name:"God Is Good",text:"GOD\nIS GOOD",font:"'Anton',sans-serif",fs:"2.5rem",tc:"#fbbf24",bg:"#1a1a2e",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f06",cat:"faith",name:"He Is Risen",text:"HE IS\nRISEN",font:"'Graduate',cursive",fs:"2.2rem",tc:"#ffffff",bg:"#7c3aed",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f07",cat:"faith",name:"Fearless",text:"FEAR-LESS",font:"'Bebas Neue',sans-serif",fs:"2.8rem",tc:"#ffffff",bg:"#166534",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f08",cat:"faith",name:"Joy Is My Superpower",text:"JOY IS MY\nSUPERPOWER",font:"'Bungee',cursive",fs:"1.5rem",tc:"#fbbf24",bg:"#0a0a0a",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f09",cat:"faith",name:"Peace Be Still",text:"PEACE\nBE STILL",font:"'Dancing Script',cursive",fs:"2rem",tc:"#ffffff",bg:"#0c4a6e",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f10",cat:"faith",name:"Trust The Lord",text:"TRUST\nTHE LORD",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#fbbf24",bg:"#1e3a5f",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f11",cat:"faith",name:"Grace Upon Grace",text:"GRACE\nUPON GRACE",font:"'Dancing Script',cursive",fs:"1.8rem",tc:"#f9a8d4",bg:"#1e3a5f",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f12",cat:"faith",name:"Chosen",text:"CHOSEN +",font:"'Bebas Neue',sans-serif",fs:"3rem",tc:"#fbbf24",bg:"#1a1a2e",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f13",cat:"faith",name:"His Mercies New",text:"HIS MERCIES\nANEW\nEVERY MORNING",font:"'Playfair Display',serif",fs:"1.2rem",tc:"#ffffff",bg:"#0c4a6e",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f14",cat:"faith",name:"Strong In The Lord",text:"STRONG\nIN THE LORD",font:"'Russo One',sans-serif",fs:"1.9rem",tc:"#fbbf24",bg:"#1a1a2e",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f15",cat:"faith",name:"Not My Will",text:"NOT MY\nWILL BUT\nTHINE",font:"'Playfair Display',serif",fs:"1.5rem",tc:"#ffffff",bg:"#292524",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f16",cat:"faith",name:"Set Apart",text:"SET\nAPART",font:"'Bebas Neue',sans-serif",fs:"3rem",tc:"#ffffff",bg:"#166534",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f17",cat:"faith",name:"Anchored In Faith",text:"ANCHORED\nIN FAITH",font:"'Lobster',cursive",fs:"1.8rem",tc:"#60a5fa",bg:"#0c4a6e",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f18",cat:"faith",name:"Overflow",text:"OVERFLOW +",font:"'Dancing Script',cursive",fs:"2.2rem",tc:"#fbbf24",bg:"#1e3a5f",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f19",cat:"faith",name:"Light And Salt",text:"LIGHT\n& SALT",font:"'Playfair Display',serif",fs:"2rem",tc:"#ffffff",bg:"#0f172a",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},
  {id:"f20",cat:"faith",name:"Sunday Best",text:"SUNDAY\nBEST",font:"'Lobster',cursive",fs:"2.2rem",tc:"#fbbf24",bg:"#1c1917",items:[...AP,"mug","tote_bag","pillow","poster","greeting_card"]},

  {id:"fu01",cat:"funny",name:"Powered By Coffee",text:"POWERED\nBY COFFEE",font:"'Bungee',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#6f4e37", badge:"Fan Fav",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu02",cat:"funny",name:"Adulting Is Hard",text:"ADULTING\nIS HARD",font:"'Permanent Marker',cursive",fs:"1.6rem",tc:"#000000",bg:"#fde047",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu03",cat:"funny",name:"404 Sleep Not Found",text:"404:\nSLEEP NOT FOUND",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu04",cat:"funny",name:"Ctrl Z My Life",text:"CTRL + Z\nMY LIFE",font:"'Space Mono',monospace",fs:"1.3rem",tc:"#ffffff",bg:"#1e1b4b",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu05",cat:"funny",name:"Sarcasm Loading",text:"SARCASM\nLOADING",font:"'Space Mono',monospace",fs:"1.3rem",tc:"#00ff41",bg:"#0a0a0a",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu06",cat:"funny",name:"I Survived Mondays",text:"I SURVIVED\nMONDAYS",font:"'Bungee',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#b91c1c",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu07",cat:"funny",name:"Plot Twist",text:"PLOT\nTWIST",font:"'Bebas Neue',sans-serif",fs:"3rem",tc:"#ffffff",bg:"#6d28d9",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu08",cat:"funny",name:"Weekend Mode On",text:"WEEKEND\nMODE: ON",font:"'Anton',sans-serif",fs:"2rem",tc:"#000000",bg:"#86efac",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu09",cat:"funny",name:"My Personality Is WiFi",text:"MY PERSONALITY\nIS MY\nWiFi PASSWORD",font:"'Caveat',cursive",fs:"1.1rem",tc:"#000000",bg:"#f1f5f9",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu10",cat:"funny",name:"Hot Mess Express",text:"HOT MESS\nEXPRESS",font:"'Bungee',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#dc2626",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu11",cat:"funny",name:"Running On Spite",text:"RUNNING ON\nSPITE\n& CAFFEINE",font:"'Anton',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#1a1a2e",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu12",cat:"funny",name:"Nap Champion",text:"NAP\nCHAMPION",font:"'Ultra',serif",fs:"1.8rem",tc:"#ffffff",bg:"#4f46e5",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu13",cat:"funny",name:"Professional Snooze",text:"PROFESSIONAL\nSNOOZE\nBUTTON PRESSER",font:"'Caveat',cursive",fs:"1.1rem",tc:"#000000",bg:"#e0f2fe",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu14",cat:"funny",name:"Not A Morning Person",text:"NOT A\nMORNING PERSON",font:"'Caveat',cursive",fs:"1.8rem",tc:"#111111",bg:"#f9f8f5",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu15",cat:"funny",name:"Overthinking Champion",text:"OVER-\nTHINKER\nCHAMPION",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#000000",bg:"#fce7f3",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu16",cat:"funny",name:"Professionally Lost",text:"PROFESSION-\nALLY LOST",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#374151",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu17",cat:"funny",name:"Error 404 Motivation",text:"ERROR 404\nMOTIVATION\nNOT FOUND",font:"'Space Mono',monospace",fs:"0.95rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu18",cat:"funny",name:"Functioning Disaster",text:"FUNCTIONING\nDISASTER",font:"'Bungee',cursive",fs:"1.6rem",tc:"#fbbf24",bg:"#111111",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu19",cat:"funny",name:"Technically Working",text:"TECHNICALLY\nWORKING",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu20",cat:"funny",name:"Social Battery 2 Percent",text:"SOCIAL\nBATTERY: 2%",font:"'Space Mono',monospace",fs:"1.2rem",tc:"#ef4444",bg:"#0f172a",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu21",cat:"funny",name:"Internet Explorer Speed",text:"MOVING AT\nINTERNET\nEXPLORER SPEED",font:"'Caveat',cursive",fs:"1.1rem",tc:"#000000",bg:"#f1f5f9",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu22",cat:"funny",name:"Do Not Pet I Am Feral",text:"DO NOT PET\nI AM FERAL",font:"'Anton',sans-serif",fs:"1.9rem",tc:"#fbbf24",bg:"#111111",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu23",cat:"funny",name:"Procrastinator Pro",text:"FINISHING\nTHIS\nLATER",font:"'Permanent Marker',cursive",fs:"1.3rem",tc:"#000000",bg:"#fde047",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu24",cat:"funny",name:"WiFi Dropped Life On Hold",text:"LIFE ON HOLD\nWiFi DROPPED",font:"'Space Mono',monospace",fs:"1rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu25",cat:"funny",name:"My Plant Has More Friends",text:"MY PLANT\nHAS MORE\nFRIENDS",font:"'Caveat',cursive",fs:"1rem",tc:"#000000",bg:"#dcfce7",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu26",cat:"funny",name:"Mentally Out Of Office",text:"MENTALLY\nOUT OF\nOFFICE",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#1d3461",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu27",cat:"funny",name:"Meeting Shouldve Been Email",text:"THIS MEETING\nCOULD HAVE\nBEEN AN EMAIL",font:"'Space Mono',monospace",fs:"0.85rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu28",cat:"funny",name:"Snack-Driven Development",text:"SNACK-DRIVEN\nDEVELOPMENT",font:"'Bungee',cursive",fs:"1.3rem",tc:"#fbbf24",bg:"#0f172a",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu29",cat:"funny",name:"Cat Dad Reluctantly",text:"CAT DAD\n(reluctantly)",font:"'Caveat',cursive",fs:"1.8rem",tc:"#000000",bg:"#fef3c7",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"fu30",cat:"funny",name:"Dog Mom By Choice",text:"DOG MOM\n(by choice)",font:"'Dancing Script',cursive",fs:"1.8rem",tc:"#f9a8d4",bg:"#fce7f3",items:[...AP,"mug","pillow","phone_case","apron","tote_bag"]},
  {id:"l01",cat:"lifestyle",name:"Good Vibes Only",text:"Good\nVibes Only",font:"'Pacifico',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#e85d04", badge:"Summer",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l02",cat:"lifestyle",name:"Born Free",text:"BORN\nFREE",font:"'Bebas Neue',sans-serif",fs:"3rem",tc:"#f39c12",bg:"#1d3461",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l03",cat:"lifestyle",name:"Choose Happy",text:"Choose\nHappy",font:"'Caveat',cursive",fs:"2rem",tc:"#ffffff",bg:"#16a34a",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l04",cat:"lifestyle",name:"Wanderlust",text:"WANDER-\nLUST",font:"'Oswald',sans-serif",fs:"2.2rem",tc:"#ffffff",bg:"#0369a1",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l05",cat:"lifestyle",name:"Stay Wild",text:"STAY\nWILD",font:"'Bungee',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#1e1b4b",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l06",cat:"lifestyle",name:"Main Character Energy",text:"MAIN\nCHARACTER\nENERGY",font:"'Anton',sans-serif",fs:"1.6rem",tc:"#ffffff",bg:"#831843",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l07",cat:"lifestyle",name:"Chasing Sunsets",text:"CHASING\nSUNSETS",font:"'Pacifico',cursive",fs:"1.6rem",tc:"#f97316",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l08",cat:"lifestyle",name:"Soft Life",text:"SOFT\nLIFE +",font:"'Dancing Script',cursive",fs:"2.5rem",tc:"#f9a8d4",bg:"#4a044e",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l09",cat:"lifestyle",name:"Collect Moments",text:"COLLECT\nMOMENTS",font:"'Playfair Display',serif",fs:"1.7rem",tc:"#ffffff",bg:"#292524",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l10",cat:"lifestyle",name:"Romanticize Your Life",text:"ROMANTICIZE\nYOUR LIFE",font:"'Dancing Script',cursive",fs:"1.6rem",tc:"#7c3aed",bg:"#faf5ff",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l11",cat:"lifestyle",name:"Local Everything",text:"LOCAL\nEVERYTHING",font:"'Graduate',cursive",fs:"2rem",tc:"#ffffff",bg:"#166534",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l12",cat:"lifestyle",name:"Coffee Shop Regular",text:"COFFEE SHOP\nREGULAR",font:"'Pacifico',cursive",fs:"1.5rem",tc:"#92400e",bg:"#fef3c7",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l13",cat:"lifestyle",name:"Golden Hour Girl",text:"GOLDEN\nHOUR GIRL",font:"'Dancing Script',cursive",fs:"2rem",tc:"#f97316",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l14",cat:"lifestyle",name:"Bookworm",text:"BOOKWORM",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#ffffff",bg:"#292524",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l15",cat:"lifestyle",name:"Crazy Plant Lady",text:"CRAZY\nPLANT LADY",font:"'Lobster',cursive",fs:"1.7rem",tc:"#ffffff",bg:"#166534",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l16",cat:"lifestyle",name:"Adventure Awaits",text:"ADVENTURE\nAWAITS",font:"'Graduate',cursive",fs:"1.7rem",tc:"#ffffff",bg:"#166534",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l17",cat:"lifestyle",name:"Kind Is Cool",text:"KIND\nIS COOL",font:"'Lobster',cursive",fs:"2.2rem",tc:"#ffffff",bg:"#0891b2",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l18",cat:"lifestyle",name:"Weekend Warrior",text:"WEEKEND\nWARRIOR",font:"'Russo One',sans-serif",fs:"1.8rem",tc:"#000000",bg:"#fbbf24",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l19",cat:"lifestyle",name:"Sunkissed",text:"SUNKISSED",font:"'Pacifico',cursive",fs:"1.8rem",tc:"#000000",bg:"#fde047",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},
  {id:"l20",cat:"lifestyle",name:"Sunflower Energy",text:"SUNFLOWER\nENERGY",font:"'Dancing Script',cursive",fs:"1.6rem",tc:"#92400e",bg:"#fef3c7",items:[...AP,...HAT,"tote_bag","mug","pillow","poster","phone_case","water_bottle"]},

  {id:"mn01",cat:"minimal",name:"Stay True",text:"STAY TRUE",font:"'Oswald',sans-serif",fs:"2rem",tc:"#0a0a0a",bg:"#f9f8f5",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn02",cat:"minimal",name:"Original Since Day One",text:"ORIGINAL\nSINCE DAY ONE",font:"'Roboto Condensed',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#0a0a0a", badge:"Clean",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn03",cat:"minimal",name:"Less Is More",text:"less\nis more.",font:"'DM Sans',sans-serif",fs:"1.6rem",tc:"#111111",bg:"#f5f5f0",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn04",cat:"minimal",name:"Breathe",text:"breathe.",font:"'Dancing Script',cursive",fs:"2.5rem",tc:"#065f46",bg:"#ecfdf5",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn05",cat:"minimal",name:"Presence",text:"PRESENCE",font:"'Bebas Neue',sans-serif",fs:"2.8rem",tc:"#374151",bg:"#f9fafb",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn06",cat:"minimal",name:"Just Start",text:"just\nstart.",font:"'Caveat',cursive",fs:"2.2rem",tc:"#1f2937",bg:"#fff7ed",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn07",cat:"minimal",name:"Make It Happen",text:"make it\nhappen.",font:"'Space Mono',monospace",fs:"1.3rem",tc:"#0a0a0a",bg:"#e8c4a0",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn08",cat:"minimal",name:"Geometric Lines",text:"- - -\n------",font:"'Space Mono',monospace",fs:"1.5rem",tc:"#6b7280",bg:"#f9f8f5",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn09",cat:"minimal",name:"Silence Is Golden",text:"SILENCE\nIS GOLDEN",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#92400e",bg:"#fef3c7",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn10",cat:"minimal",name:"Noon",text:"noon.",font:"'Space Mono',monospace",fs:"2rem",tc:"#111111",bg:"#f9f8f5",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn11",cat:"minimal",name:"Black On Black",text:"- - -",font:"'Space Mono',monospace",fs:"2rem",tc:"#222222",bg:"#111111",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn12",cat:"minimal",name:"Clean Simple Precise",text:"CLEAN\nSIMPLE\nPRECISE",font:"'Plus Jakarta Sans',sans-serif",fs:"1.6rem",tc:"#ffffff",bg:"#0f172a",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn13",cat:"minimal",name:"The Void",text:"THE\nVOID",font:"'Bebas Neue',sans-serif",fs:"2.8rem",tc:"#374151",bg:"#f9fafb",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn14",cat:"minimal",name:"Archive",text:"ARCHIVE",font:"'Oswald',sans-serif",fs:"2.5rem",tc:"#6b7280",bg:"#f9f8f5",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn15",cat:"minimal",name:"Core",text:"CORE +",font:"'Plus Jakarta Sans',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#0f172a",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn16",cat:"minimal",name:"Typewriter",text:"these words\n-",font:"'Courier New',monospace",fs:"1.5rem",tc:"#111111",bg:"#f9f8f5",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn17",cat:"minimal",name:"Dot Grid",text:". . .\n. . .",font:"'Space Mono',monospace",fs:"1.2rem",tc:"#d1d5db",bg:"#f9f8f5",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn18",cat:"minimal",name:"Lowercase Era",text:"lowercase\nera.",font:"'DM Sans',sans-serif",fs:"1.8rem",tc:"#374151",bg:"#f9fafb",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn19",cat:"minimal",name:"Diamond Mark",text:"*",font:"'Space Mono',monospace",fs:"3rem",tc:"#e85d04",bg:"#f9f8f5",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},
  {id:"mn20",cat:"minimal",name:"Minimal Stripes",text:"---  ---\n---------",font:"'Space Mono',monospace",fs:"1.5rem",tc:"#374151",bg:"#f9fafb",items:[...AP,"poster","pillow","mug","tote_bag","notebook","phone_case","mousepad"]},

  {id:"v01",cat:"vintage",name:"Est 1969",text:"EST.\n1969",font:"'Graduate',cursive",fs:"2.2rem",tc:"#d97706",bg:"#292524",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v02",cat:"vintage",name:"Rock And Roll",text:"ROCK\n& ROLL",font:"'Bungee',cursive",fs:"1.8rem",tc:"#ef4444",bg:"#111111", badge:"Classic",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v03",cat:"vintage",name:"Old School",text:"OLD\nSCHOOL",font:"'Ultra',serif",fs:"2rem",tc:"#fbbf24",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v04",cat:"vintage",name:"Keep It Classic",text:"KEEP IT\nCLASSIC",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#f5f5f4",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v05",cat:"vintage",name:"Road Trip",text:"ROAD\nTRIP +",font:"'Graduate',cursive",fs:"2rem",tc:"#fbbf24",bg:"#7c2d12",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v06",cat:"vintage",name:"Garage Band",text:"GARAGE\nBAND",font:"'Permanent Marker',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#111111",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v07",cat:"vintage",name:"Retro Wave",text:"RETRO\nWAVE",font:"'Bungee',cursive",fs:"2rem",tc:"#f0abfc",bg:"#1e1b4b",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v08",cat:"vintage",name:"Born In The 80s",text:"BORN IN\nTHE 80s",font:"'Anton',sans-serif",fs:"2rem",tc:"#fbbf24",bg:"#1a1a2e",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v09",cat:"vintage",name:"Vintage Vibes Only",text:"VINTAGE\nVIBES ONLY",font:"'Lobster',cursive",fs:"1.7rem",tc:"#d97706",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v10",cat:"vintage",name:"Drive-In Ready",text:"DRIVE-IN\nREADY",font:"'Graduate',cursive",fs:"1.8rem",tc:"#fbbf24",bg:"#111111",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v11",cat:"vintage",name:"Diner Mood",text:"DINER\nMOOD 24/7",font:"'Bungee',cursive",fs:"1.7rem",tc:"#ef4444",bg:"#fde047",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v12",cat:"vintage",name:"Analog Life",text:"ANALOG\nLIFE",font:"'Permanent Marker',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#292524",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v13",cat:"vintage",name:"Record Collector",text:"RECORD\nCOLLECTOR",font:"'Graduate',cursive",fs:"1.7rem",tc:"#d97706",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v14",cat:"vintage",name:"Polaroid Moment",text:"POLAROID\nMOMENT",font:"'Caveat',cursive",fs:"1.8rem",tc:"#000000",bg:"#f9f8f5",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v15",cat:"vintage",name:"Summer Of 69",text:"SUMMER\nOF 69",font:"'Graduate',cursive",fs:"2rem",tc:"#f97316",bg:"#111111",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v16",cat:"vintage",name:"Tape Deck Era",text:"TAPE DECK\nERA",font:"'Space Mono',monospace",fs:"1.5rem",tc:"#fbbf24",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v17",cat:"vintage",name:"Neon Nights",text:"NEON\nNIGHTS",font:"'Bungee',cursive",fs:"2.2rem",tc:"#f0abfc",bg:"#0c0a1e",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v18",cat:"vintage",name:"Feelin Groovy",text:"FEELIN\nGROOVY",font:"'Pacifico',cursive",fs:"1.7rem",tc:"#fbbf24",bg:"#7c2d12",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v19",cat:"vintage",name:"Classic Never Dies",text:"CLASSIC\nNEVER DIES",font:"'Playfair Display',serif",fs:"1.7rem",tc:"#d97706",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","mug"]},
  {id:"v20",cat:"vintage",name:"Midnight Rider",text:"MIDNIGHT\nRIDER",font:"'Graduate',cursive",fs:"1.9rem",tc:"#fbbf24",bg:"#111111",items:[...AP,...HAT,"tote_bag","poster","mug"]},

  {id:"n01",cat:"nature",name:"Into The Wild",text:"INTO\nTHE WILD",font:"'Graduate',cursive",fs:"2rem",tc:"#ffffff",bg:"#14532d",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n02",cat:"nature",name:"Wild And Free",text:"WILD &\nFREE",font:"'Pacifico',cursive",fs:"1.7rem",tc:"#ffffff",bg:"#065f46",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n03",cat:"nature",name:"Plant Parent",text:"PLANT\nPARENT",font:"'Caveat',cursive",fs:"2rem",tc:"#ffffff",bg:"#15803d",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n04",cat:"nature",name:"Ocean State",text:"OCEAN\nSTATE",font:"'Bebas Neue',sans-serif",fs:"2.8rem",tc:"#ffffff",bg:"#0369a1",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n05",cat:"nature",name:"Sunrise Chaser",text:"SUNRISE\nCHASER",font:"'Lobster',cursive",fs:"1.8rem",tc:"#f97316",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n06",cat:"nature",name:"Earth First",text:"EARTH\nFIRST",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#ffffff",bg:"#166534",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n07",cat:"nature",name:"Mountain High",text:"MOUNTAIN\nHIGH",font:"'Oswald',sans-serif",fs:"2.2rem",tc:"#bfdbfe",bg:"#1e3a5f",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n08",cat:"nature",name:"Forest Bathing",text:"FOREST\nBATHING",font:"'Playfair Display',serif",fs:"1.8rem",tc:"#ffffff",bg:"#166534",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n09",cat:"nature",name:"Mountains Are Calling",text:"THE\nMOUNTAINS\nARE CALLING",font:"'Graduate',cursive",fs:"1.4rem",tc:"#bfdbfe",bg:"#1e3a5f",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n10",cat:"nature",name:"Creek Week",text:"CREEK\nWEEK",font:"'Bungee',cursive",fs:"2.2rem",tc:"#ffffff",bg:"#0369a1",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n11",cat:"nature",name:"Desert Bloom",text:"DESERT\nBLOOM",font:"'Lobster',cursive",fs:"2rem",tc:"#f97316",bg:"#7c2d12",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n12",cat:"nature",name:"Last Of Wildflowers",text:"LAST OF\nTHE WILD\nFLOWERS",font:"'Dancing Script',cursive",fs:"1.4rem",tc:"#f9a8d4",bg:"#065f46",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n13",cat:"nature",name:"Camp Vibes Only",text:"CAMP\nVIBES ONLY",font:"'Graduate',cursive",fs:"1.8rem",tc:"#fbbf24",bg:"#166534",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n14",cat:"nature",name:"Hike More Worry Less",text:"HIKE MORE\nWORRY LESS",font:"'Anton',sans-serif",fs:"1.7rem",tc:"#ffffff",bg:"#14532d",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n15",cat:"nature",name:"Wildlife",text:"WILD\nLIFE",font:"'Bebas Neue',sans-serif",fs:"3rem",tc:"#fbbf24",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n16",cat:"nature",name:"She Is Wild",text:"SHE IS\nWILD",font:"'Dancing Script',cursive",fs:"2.2rem",tc:"#f9a8d4",bg:"#065f46",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n17",cat:"nature",name:"Sun Seeker",text:"SUN\nSEEKER",font:"'Pacifico',cursive",fs:"2rem",tc:"#fbbf24",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n18",cat:"nature",name:"Roots And Routes",text:"ROOTS\n& ROUTES",font:"'Oswald',sans-serif",fs:"2.2rem",tc:"#ffffff",bg:"#292524",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n19",cat:"nature",name:"Saltwater Heals",text:"SALTWATER\nHEALS",font:"'Lobster',cursive",fs:"1.8rem",tc:"#0ea5e9",bg:"#0c4a6e",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"n20",cat:"nature",name:"Golden Hour Only",text:"GOLDEN\nHOUR ONLY",font:"'Dancing Script',cursive",fs:"1.8rem",tc:"#f97316",bg:"#1c1917",items:[...AP,...HAT,"tote_bag","poster","water_bottle","blanket"]},
  {id:"mu01",cat:"music",name:"Turn It Up",text:"TURN\nIT UP",font:"'Bungee',cursive",fs:"1.9rem",tc:"#ffffff",bg:"#7c3aed",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu02",cat:"music",name:"Bass Boosted",text:"BASS\nBOOSTED",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#06b6d4",bg:"#0f172a",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu03",cat:"music",name:"Record Store Day",text:"RECORD\nSTORE DAY",font:"'Graduate',cursive",fs:"1.9rem",tc:"#f59e0b",bg:"#1c1917",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu04",cat:"music",name:"808s",text:"8 0 8 s",font:"'Space Mono',monospace",fs:"1.6rem",tc:"#f9fafb",bg:"#000000",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu05",cat:"music",name:"Frequency",text:"FREQUENCY",font:"'Bebas Neue',sans-serif",fs:"1.9rem",tc:"#a78bfa",bg:"#0c0a1e",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu06",cat:"music",name:"In My Headphones",text:"IN MY\nHEADPHONES",font:"'Anton',sans-serif",fs:"1.7rem",tc:"#ffffff",bg:"#111111",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu07",cat:"music",name:"Concert Veteran",text:"CONCERT\nVETERAN",font:"'Graduate',cursive",fs:"1.9rem",tc:"#fbbf24",bg:"#111111",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu08",cat:"music",name:"Vinyl Only",text:"VINYL\nONLY",font:"'Permanent Marker',cursive",fs:"1.6rem",tc:"#fbbf24",bg:"#1c1917",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu09",cat:"music",name:"Live Music Or Nothing",text:"LIVE MUSIC\nOR NOTHING",font:"'Anton',sans-serif",fs:"1.5rem",tc:"#ffffff",bg:"#0f172a",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu10",cat:"music",name:"Loud Is Love",text:"LOUD\nIS LOVE",font:"'Bungee',cursive",fs:"2.2rem",tc:"#ef4444",bg:"#0f172a",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu11",cat:"music",name:"Groove Theory",text:"GROOVE\nTHEORY",font:"'Lobster',cursive",fs:"2rem",tc:"#fbbf24",bg:"#111111",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu12",cat:"music",name:"Playlist Curator",text:"PLAYLIST\nCURATOR",font:"'Space Mono',monospace",fs:"1.3rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu13",cat:"music",name:"Aux Cord Rights",text:"AUX CORD\nRIGHTS +",font:"'Graduate',cursive",fs:"1.8rem",tc:"#fbbf24",bg:"#1e1b4b",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu14",cat:"music",name:"Song Not Skipped",text:"SONG NOT\nSKIPPED +",font:"'Space Mono',monospace",fs:"1.2rem",tc:"#22c55e",bg:"#0f172a",items:[...AP,"poster","phone_case","tote_bag"]},
  {id:"mu15",cat:"music",name:"Dance Floor Historian",text:"DANCE FLOOR\nHISTORIAN",font:"'Bungee',cursive",fs:"1.4rem",tc:"#f0abfc",bg:"#1e1b4b",items:[...AP,"poster","phone_case","tote_bag"]},

  {id:"fd01",cat:"foodie",name:"Taco Tuesday",text:"TACO\nTUESDAY",font:"'Bungee',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#b45309",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd02",cat:"foodie",name:"Ramen Life",text:"RAMEN\nLIFE",font:"'Pacifico',cursive",fs:"1.6rem",tc:"#fb923c",bg:"#1c1917",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd03",cat:"foodie",name:"Brunch Club",text:"BRUNCH\nCLUB",font:"'Lobster',cursive",fs:"2rem",tc:"#ffffff",bg:"#16a34a",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd04",cat:"foodie",name:"Pizza Nation",text:"PIZZA\nNATION",font:"'Anton',sans-serif",fs:"2rem",tc:"#ffffff",bg:"#dc2626",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd05",cat:"foodie",name:"Coffee Then Plans",text:"COFFEE\nTHEN PLANS",font:"'Caveat',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#6f4e37",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd06",cat:"foodie",name:"Snack Queen",text:"SNACK\nQUEEN",font:"'Bebas Neue',sans-serif",fs:"2.5rem",tc:"#fbbf24",bg:"#111111",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd07",cat:"foodie",name:"Eat Well Live Well",text:"EAT WELL\nLIVE WELL",font:"'Lobster',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#166534",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd08",cat:"foodie",name:"Butter Makes It Better",text:"BUTTER\nMAKES IT\nBETTER",font:"'Bungee',cursive",fs:"1.4rem",tc:"#fbbf24",bg:"#92400e",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd09",cat:"foodie",name:"Dumpling Obsessed",text:"DUMPLING\nOBSESSED",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#ffffff",bg:"#7c2d12",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd10",cat:"foodie",name:"Cheese Board Goals",text:"CHEESE BOARD\nGOALS",font:"'Graduate',cursive",fs:"1.5rem",tc:"#fbbf24",bg:"#292524",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd11",cat:"foodie",name:"Pasta La Vista",text:"PASTA\nLA VISTA",font:"'Lobster',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#b45309",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd12",cat:"foodie",name:"Soup Season",text:"SOUP\nSEASON",font:"'Pacifico',cursive",fs:"1.6rem",tc:"#92400e",bg:"#fef3c7",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd13",cat:"foodie",name:"Spice Level Maximum",text:"SPICE LEVEL\nMAXIMUM",font:"'Anton',sans-serif",fs:"1.7rem",tc:"#ffffff",bg:"#b91c1c",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd14",cat:"foodie",name:"Matcha Made In Heaven",text:"MATCHA MADE\nIN HEAVEN",font:"'Dancing Script',cursive",fs:"1.4rem",tc:"#166534",bg:"#f0fdf4",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd15",cat:"foodie",name:"Anything Fried",text:"ANYTHING\nFRIED",font:"'Bungee',cursive",fs:"2rem",tc:"#fbbf24",bg:"#111111",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd16",cat:"foodie",name:"Sushi Mood",text:"SUSHI\nMOOD",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#ffffff",bg:"#0c4a6e",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd17",cat:"foodie",name:"Hot Sauce Everything",text:"HOT SAUCE\nEVERYTHING",font:"'Graduate',cursive",fs:"1.5rem",tc:"#fbbf24",bg:"#7c2d12",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd18",cat:"foodie",name:"Farmers Market Regular",text:"FARMERS\nMARKET\nREGULAR",font:"'Pacifico',cursive",fs:"1.3rem",tc:"#166534",bg:"#ecfdf5",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd19",cat:"foodie",name:"Midnight Snacker",text:"MIDNIGHT\nSNACKER",font:"'Anton',sans-serif",fs:"2rem",tc:"#fbbf24",bg:"#0f172a",items:[...AP,"mug","apron","tote_bag"]},
  {id:"fd20",cat:"foodie",name:"Udon Believe It",text:"UDON\nBELIEVE IT",font:"'Bungee',cursive",fs:"1.7rem",tc:"#ffffff",bg:"#b45309",items:[...AP,"mug","apron","tote_bag"]},

  {id:"ps01",cat:"product",name:"Worlds Best Mug",text:"WORLDS\nBEST MUG",font:"'Anton',sans-serif",fs:"1.9rem",tc:"#ffffff",bg:"#6f4e37",items:["mug","travel_mug"]},
  {id:"ps02",cat:"product",name:"Coffee First",text:"COFFEE\nFIRST.\nTHEN THINGS.",font:"'Caveat',cursive",fs:"1.3rem",tc:"#92400e",bg:"#fef3c7",items:["mug","travel_mug"]},
  {id:"ps03",cat:"product",name:"Life Is Brewing",text:"LIFE IS\nBREWING",font:"'Lobster',cursive",fs:"1.8rem",tc:"#fbbf24",bg:"#6f4e37",items:["mug","travel_mug"]},
  {id:"ps04",cat:"product",name:"Cup Number Three",text:"THIS IS\nCUP 3\n(today)",font:"'Space Mono',monospace",fs:"1.2rem",tc:"#22c55e",bg:"#0f172a",items:["mug"]},
  {id:"ps05",cat:"product",name:"Sippin In Peace",text:"SIPPIN\nIN PEACE",font:"'Pacifico',cursive",fs:"1.6rem",tc:"#92400e",bg:"#fef3c7",items:["mug","travel_mug","water_bottle"]},
  {id:"ps06",cat:"product",name:"Carry On",text:"CARRY ON\n& CARRY BAGS",font:"'Bungee',cursive",fs:"1.4rem",tc:"#000000",bg:"#e8d5b7",items:["tote_bag"]},
  {id:"ps07",cat:"product",name:"Reusable Legend",text:"REUSABLE\nLEGEND",font:"'Graduate',cursive",fs:"1.9rem",tc:"#ffffff",bg:"#166534",items:["tote_bag"]},
  {id:"ps08",cat:"product",name:"Bag Lady",text:"BAG\nLADY",font:"'Anton',sans-serif",fs:"2.5rem",tc:"#000000",bg:"#e8d5b7",items:["tote_bag","drawstring"]},
  {id:"ps09",cat:"product",name:"Aesthetic Shopper",text:"AESTHETIC\nSHOPPER",font:"'Plus Jakarta Sans',sans-serif",fs:"1.4rem",tc:"#500724",bg:"#fce7f3",items:["tote_bag"]},
  {id:"ps10",cat:"product",name:"Groceries And Goals",text:"GROCERIES\n& GOALS",font:"'Caveat',cursive",fs:"1.8rem",tc:"#166534",bg:"#ecfdf5",items:["tote_bag"]},
  {id:"ps11",cat:"product",name:"Good Night",text:"GOOD\nNIGHT.",font:"'Dancing Script',cursive",fs:"2.5rem",tc:"#c084fc",bg:"#1e1b4b",items:["pillow","blanket"]},
  {id:"ps12",cat:"product",name:"Pillow Fort CEO",text:"PILLOW\nFORT CEO",font:"'Bungee',cursive",fs:"1.6rem",tc:"#e0f2fe",bg:"#0f172a",items:["pillow"]},
  {id:"ps13",cat:"product",name:"Nap Zone",text:"NAP\nZONE\nDO NOT ENTER",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#ffffff",bg:"#111111",items:["pillow"]},
  {id:"ps14",cat:"product",name:"Dream Big",text:"DREAM\nBIG",font:"'Pacifico',cursive",fs:"1.8rem",tc:"#c084fc",bg:"#1e1b4b",items:["pillow","blanket","poster"]},
  {id:"ps15",cat:"product",name:"Home Is Here",text:"HOME\nIS HERE",font:"'Lobster',cursive",fs:"1.9rem",tc:"#fbbf24",bg:"#1c1917",items:["pillow","blanket","poster"]},
  {id:"ps16",cat:"product",name:"Do Not Open",text:"DO NOT\nOPEN",font:"'Space Mono',monospace",fs:"1.4rem",tc:"#ef4444",bg:"#0f172a",items:["phone_case"]},
  {id:"ps17",cat:"product",name:"Low Battery",text:"LOW\nBATTERY",font:"'Space Mono',monospace",fs:"1.4rem",tc:"#ef4444",bg:"#0f172a",items:["phone_case"]},
  {id:"ps18",cat:"product",name:"No Notifications",text:"NO\nNOTIFICATIONS",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#22c55e",bg:"#0f172a",items:["phone_case"]},
  {id:"ps19",cat:"product",name:"Swipe Right",text:"SWIPE\nRIGHT",font:"'Lobster',cursive",fs:"1.9rem",tc:"#ef4444",bg:"#111111",items:["phone_case"]},
  {id:"ps20",cat:"product",name:"Read Your Texts",text:"READ YOUR\nTEXTS",font:"'Bungee',cursive",fs:"1.5rem",tc:"#fbbf24",bg:"#0f172a",items:["phone_case"]},
  {id:"ps21",cat:"product",name:"Git Push",text:"git push\norigin main",font:"'Space Mono',monospace",fs:"1.2rem",tc:"#22c55e",bg:"#0f172a",items:["mousepad","laptop_sleeve"]},
  {id:"ps22",cat:"product",name:"Googled It Again",text:"GOOGLED\nIT AGAIN",font:"'Space Mono',monospace",fs:"1.2rem",tc:"#22c55e",bg:"#0f172a",items:["mousepad","mug","tee"]},
  {id:"ps23",cat:"product",name:"Fullstack Dev",text:"FULLSTACK\nDEV",font:"'Bungee',cursive",fs:"1.6rem",tc:"#22c55e",bg:"#0f172a",items:["mousepad","mug","tee","laptop_sleeve"]},
  {id:"ps24",cat:"product",name:"In The Zone",text:"IN\nTHE ZONE\nDO NOT DISTURB",font:"'Space Mono',monospace",fs:"1rem",tc:"#fbbf24",bg:"#0f172a",items:["mousepad","mug"]},
  {id:"ps25",cat:"product",name:"Loading Please Wait",text:"LOADING\n\nPLEASE WAIT",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#22c55e",bg:"#0f172a",items:["mousepad","phone_case","mug"]},
  {id:"ps26",cat:"product",name:"Head Chef",text:"HEAD CHEF\n(of the house)",font:"'Graduate',cursive",fs:"1.7rem",tc:"#ffffff",bg:"#b45309",items:["apron"]},
  {id:"ps27",cat:"product",name:"Kitchen Boss",text:"KITCHEN\nBOSS",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#fbbf24",bg:"#111111",items:["apron","mug"]},
  {id:"ps28",cat:"product",name:"Sous Vide Or Die",text:"SOUS VIDE\nOR DIE",font:"'Bungee',cursive",fs:"1.5rem",tc:"#ffffff",bg:"#7c2d12",items:["apron"]},
  {id:"ps29",cat:"product",name:"Kiss The Cook",text:"KISS\nTHE COOK",font:"'Pacifico',cursive",fs:"1.6rem",tc:"#ef4444",bg:"#fef3c7",items:["apron","greeting_card"]},
  {id:"ps30",cat:"product",name:"Weekend Chef",text:"WEEKEND\nCHEF",font:"'Graduate',cursive",fs:"2rem",tc:"#fbbf24",bg:"#6f4e37",items:["apron","mug"]},
  {id:"ps31",cat:"product",name:"Odd Socks Champion",text:"ODD SOCKS\nCHAMPION",font:"'Bungee',cursive",fs:"1.4rem",tc:"#ffffff",bg:"#7c3aed",items:["socks"]},
  {id:"ps32",cat:"product",name:"These Socks Slap",text:"THESE SOCKS\nSLAP",font:"'Anton',sans-serif",fs:"1.8rem",tc:"#fbbf24",bg:"#111111",items:["socks"]},
  {id:"ps33",cat:"product",name:"Sock It To Me",text:"SOCK\nIT TO ME",font:"'Graduate',cursive",fs:"1.8rem",tc:"#ffffff",bg:"#dc2626",items:["socks"]},
  {id:"ps34",cat:"product",name:"No Show Socks Gang",text:"NO SHOW\nSOCKS GANG",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#22c55e",bg:"#0f172a",items:["socks"]},
  {id:"ps35",cat:"product",name:"Lucky Socks",text:"LUCKY\nSOCKS",font:"'Pacifico',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#166534",items:["socks"]},
  {id:"ps36",cat:"product",name:"Dad Hat Energy",text:"DAD HAT\nDAD ENERGY",font:"'Anton',sans-serif",fs:"1.7rem",tc:"#ffffff",bg:"#1c1917",items:["snapback","dadhut","beanie","bucket_hat","trucker_hat"]},
  {id:"ps37",cat:"product",name:"Fitted Hat Stan",text:"FITTED\nHAT STAN",font:"'Graduate',cursive",fs:"1.8rem",tc:"#fbbf24",bg:"#111111",items:["snapback","dadhut","trucker_hat"]},
  {id:"ps38",cat:"product",name:"I Am A Hat Person",text:"I AM A\nHAT PERSON",font:"'Bungee',cursive",fs:"1.6rem",tc:"#ffffff",bg:"#1d3461",items:["dadhut","snapback","beanie","bucket_hat"]},
  {id:"ps39",cat:"product",name:"Blanket Fort Architect",text:"BLANKET FORT\nARCHITECT",font:"'Anton',sans-serif",fs:"1.5rem",tc:"#c084fc",bg:"#1e1b4b",items:["blanket","pillow"]},
  {id:"ps40",cat:"product",name:"Cozy Season Always",text:"COZY\nSEASON\nALWAYS",font:"'Dancing Script',cursive",fs:"1.6rem",tc:"#f9a8d4",bg:"#4a044e",items:["blanket","pillow","mug"]},
  {id:"ps41",cat:"product",name:"Notes To Self",text:"NOTES\nTO SELF",font:"'Playfair Display',serif",fs:"2rem",tc:"#ffffff",bg:"#1c1917",items:["notebook"]},
  {id:"ps42",cat:"product",name:"Brain Dump",text:"BRAIN\nDUMP",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#c084fc",bg:"#1e1b4b",items:["notebook"]},
  {id:"ps43",cat:"product",name:"Planner Girlie",text:"PLANNER\nGIRLIE",font:"'Dancing Script',cursive",fs:"2rem",tc:"#f9a8d4",bg:"#fce7f3",items:["notebook"]},
  {id:"ps44",cat:"product",name:"Ideas Go Here",text:"IDEAS\nGO HERE",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#374151",bg:"#f9fafb",items:["notebook","poster"]},
  {id:"ps45",cat:"product",name:"Manifest It",text:"MANIFEST\nIT +",font:"'Dancing Script',cursive",fs:"2rem",tc:"#f9a8d4",bg:"#4a044e",items:["notebook"]},
  {id:"ps46",cat:"product",name:"Drink Your Water",text:"DRINK\nYOUR WATER",font:"'Bungee',cursive",fs:"1.5rem",tc:"#60a5fa",bg:"#0c4a6e",items:["water_bottle","mug"]},
  {id:"ps47",cat:"product",name:"Hydro Homie",text:"HYDRO\nHOMIE",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#60a5fa",bg:"#0f172a",items:["water_bottle"]},
  {id:"ps48",cat:"product",name:"Sticker Bomb Pack",text:"STICKER BOMB\nPACK +",font:"'Bungee',cursive",fs:"1.5rem",tc:"#ffffff",bg:"#7c3aed",items:["sticker_sheet"]},
  {id:"ps49",cat:"product",name:"My Laptop My Rules",text:"MY LAPTOP\nMY RULES",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#22c55e",bg:"#0f172a",items:["sticker_sheet","laptop_sleeve"]},
  {id:"ps50",cat:"product",name:"Good Energy Only",text:"GOOD\nENERGY\nONLY +",font:"'Dancing Script',cursive",fs:"1.5rem",tc:"#f9a8d4",bg:"#fce7f3",items:["sticker_sheet","notebook"]},
  {id:"ps51",cat:"product",name:"Breathe Easy",text:"BREATHE\nEASY",font:"'Bebas Neue',sans-serif",fs:"2.4rem",tc:"#ffffff",bg:"#0369a1",items:["face_mask"]},
  {id:"ps52",cat:"product",name:"Masked And Caffeinated",text:"MASKED &\nCAFFEINATED",font:"'Bungee',cursive",fs:"1.4rem",tc:"#ffffff",bg:"#6f4e37",items:["face_mask"]},
  {id:"ps53",cat:"product",name:"Fanny Pack Gang",text:"FANNY\nPACK GANG",font:"'Graduate',cursive",fs:"1.9rem",tc:"#fbbf24",bg:"#111111",items:["fanny_pack"]},
  {id:"ps54",cat:"product",name:"Good Boy",text:"GOOD\nBOY",font:"'Anton',sans-serif",fs:"2.2rem",tc:"#000000",bg:"#fde047",items:["pet_bandana","tee"]},
  {id:"ps55",cat:"product",name:"Dog Tax Required",text:"DOG TAX\nREQUIRED",font:"'Space Mono',monospace",fs:"1.1rem",tc:"#000000",bg:"#f1f5f9",items:["tote_bag","tee"]},

];

// ── CATEGORY REGISTRY ──
const DESIGN_CATEGORIES = [
  {id:"gym",          label:"Gym & Fitness",     dot:"#ef4444"},
  {id:"motivational", label:"Motivational",       dot:"#f97316"},
  {id:"puns",         label:"Puns",               dot:"#a855f7"},
  {id:"dadjokes",     label:"Dad Jokes",          dot:"#eab308"},
  {id:"teen",         label:"Gen Z / Teen",       dot:"#ec4899"},
  {id:"culture",      label:"Culture & Society",  dot:"#3b82f6"},
  {id:"faith",        label:"Faith",              dot:"#8b5cf6"},
  {id:"funny",        label:"Funny & Relatable",  dot:"#f59e0b"},
  {id:"lifestyle",    label:"Lifestyle",          dot:"#22c55e"},
  {id:"minimal",      label:"Minimal",            dot:"#6b7280"},
  {id:"vintage",      label:"Vintage",            dot:"#b45309"},
  {id:"nature",       label:"Nature & Outdoors",  dot:"#16a34a"},
  {id:"music",        label:"Music",              dot:"#6366f1"},
  {id:"foodie",       label:"Foodie",             dot:"#dc2626"},
  {id:"product",      label:"Item-Specific",      dot:"#e85d04"},
];

// ── HELPERS ──
function getDesignsForProduct(pid){return DESIGNS.filter(d=>d.items&&d.items.includes(pid));}
function getDesignsByCategory(cat){return DESIGNS.filter(d=>d.cat===cat);}
